// Frozen copy of the tour manifest formerly code-generated (by
// scripts/features/generate.ts) from features/devstory-triage.yaml.
//
// devstory-triage was de-listed from the feature catalog: it's an external
// stub (its story lives in an external checkout outside this repo, never
// recordable here) that features/AGENTS.md's completeness rules can no longer
// justify keeping cataloged. devstory-triage-video.spec.ts is kept intact per
// the de-listing decision, so this array is frozen here (no longer regenerated
// from YAML) purely to keep that spec's driving logic working. Do not "fix"
// drift against a YAML that no longer exists — if the spec needs new steps,
// edit this file directly.

import { type TourStep } from "../../src/tour/types.js";

// Re-export so the Playwright spec can import the step type alongside the array.
export type { TourStep };

export const DEVSTORY_TRIAGE_TOUR_STEPS: readonly TourStep[] = [
  {
    id: "ds-intro-home",
    route: "home",
    title: "From bug queue to fix pipeline",
    body: "devstory models an engineer's day as one deterministic state-machine graph. This tour walks the front half: triage a bug queue, score the candidates, drill into the worst one, and hand it off into the autonomous bugfix pipeline — every room replayed the same way every time, no LLM in the loop.",
    placement: "center",
    kind: "explain",
    advance: "next",
    waitForTarget: "home-view",
    dwellMs: 5500,
  },
  {
    id: "ds-intro-story",
    route: "home",
    target: "story-card",
    title: "The devstory",
    body: "This card is devstory — it imports a triage gate and the bugfix pipeline and folds them into one graph. We'll open the triage queue, pick a fixable ticket, and watch the @exit:fixable handoff carry it straight into the pipeline. Let's run it.",
    placement: "right",
    kind: "explain",
    advance: "next",
    waitForTarget: "story-card",
    dwellMs: 5000,
  },
  {
    id: "ds-intro-start",
    route: "home",
    target: "new-session-btn",
    title: "Spin up a run",
    body: "Click New session to create a fresh, independently-traced run of devstory.",
    placement: "right",
    kind: "action",
    advance: "route-match",
    advanceRoute: "interactive",
    waitForTarget: "new-session-btn",
    dwellMs: 3500,
  },
  {
    id: "ds-intro-observe",
    route: "interactive",
    target: "observe-link",
    title: "Drive here, observe there",
    body: "We're on the drive view: pick intents, submit turns, and watch the state badge advance one room at a time. The Observe link opens the read-only observer for this same run — the trace tree, timeline, and graph. We'll drive the whole triage + handoff from here.",
    placement: "bottom",
    kind: "explain",
    advance: "next",
    waitForTarget: "observe-link",
    dwellMs: 5000,
  },
  {
    id: "ds-triage-open",
    route: "any",
    target: "intent-btn-go_triage",
    title: "Open the bug-queue triage",
    body: "The engineer's day starts in triage. go_triage steps from the main room into the bug-queue triage gate — a read-only room that scores a Jira queue cheaply so a doomed ticket never burns a multi-minute pipeline run.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "intent-btn-go_triage",
    dwellMs: 5000,
  },
  {
    id: "ds-triage-jql",
    route: "any",
    target: "composer-input",
    title: "Point it at a queue",
    body: "We set the JQL the scan will triage — every open ABR bug. The queue room is the resting state of the loop: configure a query, then scan it into a ranked candidate list.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "composer-input",
    dwellMs: 5000,
  },
  {
    id: "ds-triage-survey",
    route: "any",
    target: "chat-transcript",
    title: "The ranked candidate list",
    body: "scan scores each ticket against five rubric dimensions and ranks them by verdict: ABR-429271 leads with a 🟢 HIGH (P1, local repro), then two 🟡 MEDIUMs, then the 🔴 LOWs. Eight scored out of twenty-three matched — the worst-but-fixable bug surfaces first.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "chat-transcript",
    dwellMs: 6500,
  },
  {
    id: "ds-triage-card",
    route: "any",
    target: "chat-transcript",
    title: "The triage card — the verdict & rubric",
    body: "Selecting ABR-429271 opens its full triage card: a 🟢 HIGH verdict at 0.91 confidence, the five rubric dimensions each with evidence (reproducibility, localization, blast radius, test coverage, fix clarity), and the resolved project + repo. This is the call — is the bug worth an autonomous fix? The card says yes: Ready.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "chat-transcript",
    dwellMs: 7500,
  },
  {
    id: "ds-handoff",
    route: "any",
    target: "intent-btn-triage__accept",
    title: "Accept — hand off to the pipeline",
    body: "accept fires triage's @exit:fixable handoff: it carries the triaged ticket (and its resolved repo + exec mode) across the story boundary into the imported bugfix pipeline. The run lands in bf.ticket_setup, pre-seeded — ticket found, local mode, ready to launch.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "intent-btn-triage__accept",
    dwellMs: 6000,
  },
  {
    id: "ds-pipeline-kickoff",
    route: "any",
    target: "intent-btn-bf__start_pipeline",
    title: "Kick off the pipeline",
    body: "start_pipeline launches the autonomous bugfix pipeline for ABR-429271. The run enters bf.phase_minus_1_executing — the first pipeline phase. From here the agent owns the fix end to end: reproduce → propose → implement → test → review → validate → open a PR. That full walk is the next tour.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "intent-btn-bf__start_pipeline",
    dwellMs: 6000,
  },
  {
    id: "ds-done",
    route: "any",
    target: "state-badge",
    title: "Handoff complete — pipeline running",
    body: "That's the front half of the engineer's day: a bug queue triaged, the worst fixable ticket chosen on the strength of its rubric, and handed across a story boundary into an autonomous pipeline that's now executing — all one deterministic, replayable graph. Hit '?' anytime to replay this tour.",
    placement: "left",
    kind: "explain",
    advance: "next",
    waitForTarget: "state-badge",
    dwellMs: 6000,
  },
];
