package dynamicworkflow

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	goyaml "github.com/goccy/go-yaml"

	"kitsoki/internal/app"
	"kitsoki/internal/testrunner"
)

const (
	// DefaultTemplateStoryDir is the reusable story package copied into each
	// draft. It is a generic manifest-driven workflow runner, so a generated
	// workflow is just a punch-list manifest plus a story copy.
	DefaultTemplateStoryDir = "stories/punch-list"

	// DefaultOutputDir is the scratch root for generated workflow packages.
	DefaultOutputDir = ".artifacts/dynamic-workflows"

	// ManifestVersion is the manifest schema generated by this package.
	ManifestVersion = "punch-list/v1"
)

// Service owns the dynamic-workflow draft lifecycle.
type Service struct {
	RootDir            string
	OutputDir          string
	TemplateStoryDir   string
	Now                func() time.Time
	GenerateWorkflowID func(GenerateRequest) string
}

// GenerateRequest captures the operator request being turned into a workflow.
type GenerateRequest struct {
	Goal   string
	Slug   string
	Story  string
	Prompt string
}

// CreateRequest is the input to Create.
type CreateRequest struct {
	Goal string
	Slug string
}

// ExportRequest controls the promotion/export destination.
type ExportRequest struct {
	TargetDir      string
	AllowBaseStory bool
}

// ValidationReport is the deterministic check result for a workflow draft.
type ValidationReport struct {
	OK       bool     `json:"ok"`
	Errors   []string `json:"errors,omitempty"`
	Warnings []string `json:"warnings,omitempty"`
}

// ExportReport is the deterministic promotion/export summary written beside a
// promoted workflow package.
type ExportReport struct {
	WorkflowID      string   `json:"workflow_id"`
	ExportPath      string   `json:"export_path"`
	Status          string   `json:"status"`
	Artifacts       []string `json:"artifacts,omitempty"`
	StarterFlowPath string   `json:"starter_flow_path,omitempty"`
	StarterCassette string   `json:"starter_cassette_path,omitempty"`
	Warnings        []string `json:"warnings,omitempty"`
	Todos           []string `json:"todos,omitempty"`
	BaseStory       bool     `json:"base_story,omitempty"`
}

// Receipt is the common artifact/trackable shape returned by create/validate/
// launch/export. It is written to receipt.json in the draft directory.
type Receipt struct {
	WorkflowID       string           `json:"workflow_id"`
	Goal             string           `json:"goal"`
	Slug             string           `json:"slug"`
	CreatedAt        time.Time        `json:"created_at"`
	DraftDir         string           `json:"draft_dir"`
	TemplateStoryDir string           `json:"template_story_dir"`
	AppPath          string           `json:"app_path"`
	ManifestPath     string           `json:"manifest_path"`
	LaunchBasisPath  string           `json:"launch_basis_path"`
	TracePath        string           `json:"trace_path,omitempty"`
	EventsPath       string           `json:"events_path,omitempty"`
	LaunchCommand    string           `json:"launch_command,omitempty"`
	Validation       ValidationReport `json:"validation"`
	ValidationPath   string           `json:"validation_path,omitempty"`
	ExportPath       string           `json:"export_path,omitempty"`
	ExportReportPath string           `json:"export_report_path,omitempty"`
	SessionID        string           `json:"session_id,omitempty"`
	SessionHandle    string           `json:"session_handle,omitempty"`
	URL              string           `json:"url,omitempty"`
}

// Manifest is the punch-list manifest emitted for the workflow.
type Manifest struct {
	Version  string           `yaml:"version"`
	Defaults ManifestDefaults `yaml:"defaults"`
	Items    []ManifestItem   `yaml:"items"`
}

// ManifestDefaults are copied onto each generated item.
type ManifestDefaults struct {
	Harness           string `yaml:"harness"`
	Profile           string `yaml:"profile"`
	Model             string `yaml:"model"`
	TraceRoot         string `yaml:"trace_root"`
	RequireTraceModel bool   `yaml:"require_trace_model,omitempty"`
}

// ManifestItem is one row in the generated punch-list manifest.
type ManifestItem struct {
	ID                   string           `yaml:"id"`
	Title                string           `yaml:"title"`
	Priority             int              `yaml:"priority"`
	Story                string           `yaml:"story"`
	Mode                 string           `yaml:"mode"`
	Prompt               string           `yaml:"prompt"`
	ImplementationStory  string           `yaml:"implementation_story,omitempty"`
	ImplementationPrompt string           `yaml:"implementation_prompt,omitempty"`
	GateCommand          string           `yaml:"gate_command,omitempty"`
	Verify               []ManifestVerify `yaml:"verify"`
}

// ManifestVerify is one deterministic check in the manifest.
type ManifestVerify struct {
	Kind  string `yaml:"kind"`
	Story string `yaml:"story,omitempty"`
	Cmd   string `yaml:"cmd,omitempty"`
	Flows string `yaml:"flows,omitempty"`
}

var unsafeSlug = regexp.MustCompile(`[^a-zA-Z0-9._-]+`)

// NewService returns a service rooted at repoRoot. The outputDir defaults to
// .artifacts/dynamic-workflows under the root and the template story defaults to
// stories/punch-list.
func NewService(repoRoot string) *Service {
	return &Service{
		RootDir:          repoRoot,
		OutputDir:        filepath.Join(repoRoot, DefaultOutputDir),
		TemplateStoryDir: filepath.Join(repoRoot, DefaultTemplateStoryDir),
		Now:              time.Now,
	}
}

func (s *Service) ensure() {
	if s.Now == nil {
		s.Now = time.Now
	}
	if s.OutputDir == "" {
		base := s.RootDir
		if base == "" {
			base = "."
		}
		s.OutputDir = filepath.Join(base, DefaultOutputDir)
	}
	if s.TemplateStoryDir == "" {
		base := s.RootDir
		if base == "" {
			base = "."
		}
		s.TemplateStoryDir = filepath.Join(base, DefaultTemplateStoryDir)
	}
	if s.GenerateWorkflowID == nil {
		now := s.Now
		s.GenerateWorkflowID = func(req GenerateRequest) string {
			when := now().UTC().Format("20060102T150405Z")
			base := workflowSlug(req.Slug, req.Goal)
			if base == "" {
				base = "workflow"
			}
			return "dwf_" + when + "_" + base
		}
	}
}

// Create writes a new draft package and receipt.
func (s *Service) Create(ctx context.Context, req CreateRequest) (*Receipt, error) {
	_ = ctx
	s.ensure()
	genReq := GenerateRequest{Goal: req.Goal, Slug: req.Slug, Story: s.TemplateStoryDir, Prompt: req.Goal}
	workflowID := s.GenerateWorkflowID(genReq)
	if workflowID == "" {
		return nil, fmt.Errorf("dynamicworkflow: empty workflow id")
	}
	draftDir := filepath.Join(s.OutputDir, workflowID)
	if err := os.MkdirAll(draftDir, 0o755); err != nil {
		return nil, fmt.Errorf("dynamicworkflow: create draft dir: %w", err)
	}
	appPath := filepath.Join(draftDir, "app")
	manifestPath := filepath.Join(draftDir, "manifest.yaml")
	launchBasisPath := filepath.Join(draftDir, "launch.yaml")
	validationPath := filepath.Join(draftDir, "validation.json")
	eventsPath := filepath.Join(draftDir, "events.jsonl")
	receiptPath := filepath.Join(draftDir, "receipt.json")
	exportReportPath := filepath.Join(draftDir, "export-report.json")

	if err := copyDir(s.TemplateStoryDir, appPath); err != nil {
		return nil, err
	}

	manifest := s.buildManifest(genReq, workflowID, appPath, manifestPath)
	if err := writeYAML(manifestPath, manifest); err != nil {
		return nil, err
	}
	if err := writeLaunchBasis(launchBasisPath, manifestPath); err != nil {
		return nil, err
	}

	report := s.ValidateDraft(appPath, manifestPath)
	if err := writeJSON(validationPath, report); err != nil {
		return nil, err
	}
	receipt := &Receipt{
		WorkflowID:       workflowID,
		Goal:             req.Goal,
		Slug:             workflowSlug(req.Slug, req.Goal),
		CreatedAt:        s.Now().UTC(),
		DraftDir:         draftDir,
		TemplateStoryDir: s.TemplateStoryDir,
		AppPath:          appPath,
		ManifestPath:     manifestPath,
		LaunchBasisPath:  launchBasisPath,
		TracePath:        filepath.Join(draftDir, "trace.jsonl"),
		EventsPath:       eventsPath,
		Validation:       report,
		ValidationPath:   validationPath,
		ExportReportPath: exportReportPath,
	}
	if report.OK {
		receipt.LaunchCommand = fmt.Sprintf("kitsoki run %s --warp %s", quoteArg(filepath.Join(appPath, "app.yaml")), quoteArg(launchBasisPath))
	}
	if err := writeJSON(receiptPath, receipt); err != nil {
		return nil, err
	}
	if err := appendWorkflowEvent(eventsPath, map[string]any{
		"kind":            "dynamic.workflow.generated",
		"workflow_id":     workflowID,
		"at":              s.nowUTC(),
		"goal":            req.Goal,
		"slug":            receipt.Slug,
		"draft_dir":       draftDir,
		"app_path":        appPath,
		"manifest_path":   manifestPath,
		"manifest_hash":   mustHashFile(manifestPath),
		"launch_basis":    launchBasisPath,
		"trace_path":      receipt.TracePath,
		"validation_path": validationPath,
		"validation":      report,
		"receipt_path":    receiptPath,
		"receipt_hash":    mustHashFile(receiptPath),
	}); err != nil {
		return nil, err
	}
	if err := appendWorkflowEvent(eventsPath, map[string]any{
		"kind":            "dynamic.workflow.validated",
		"workflow_id":     workflowID,
		"at":              s.nowUTC(),
		"app_path":        appPath,
		"manifest_path":   manifestPath,
		"validation_path": validationPath,
		"validation_hash": mustHashFile(validationPath),
		"ok":              report.OK,
		"errors":          report.Errors,
		"warnings":        report.Warnings,
	}); err != nil {
		return nil, err
	}
	return receipt, nil
}

// Launch resolves the draft receipt and ensures it is validated before launch.
// The caller is responsible for creating any live session handle; this method
// just normalizes the launch receipt shape and persists it.
func (s *Service) Launch(ctx context.Context, workflowID string) (*Receipt, error) {
	_ = ctx
	s.ensure()
	receipt, err := s.ReadReceipt(workflowID)
	if err != nil {
		return nil, err
	}
	if !receipt.Validation.OK {
		receipt.Validation = s.ValidateDraft(receipt.AppPath, receipt.ManifestPath)
		if err := writeJSON(filepath.Join(s.OutputDir, receipt.WorkflowID, "receipt.json"), receipt); err != nil {
			return nil, err
		}
		if err := appendWorkflowEvent(receipt.EventsPath, map[string]any{
			"kind":            "dynamic.workflow.validated",
			"workflow_id":     receipt.WorkflowID,
			"at":              s.nowUTC(),
			"app_path":        receipt.AppPath,
			"manifest_path":   receipt.ManifestPath,
			"validation_path": receipt.ValidationPath,
			"validation_hash": mustHashFile(receipt.ValidationPath),
			"ok":              receipt.Validation.OK,
			"errors":          receipt.Validation.Errors,
			"warnings":        receipt.Validation.Warnings,
		}); err != nil {
			return nil, err
		}
	}
	if !receipt.Validation.OK {
		return nil, fmt.Errorf("dynamicworkflow: workflow %s is not validated", receipt.WorkflowID)
	}
	if receipt.TracePath == "" {
		receipt.TracePath = filepath.Join(s.OutputDir, receipt.WorkflowID, "trace.jsonl")
	}
	if receipt.LaunchCommand == "" {
		receipt.LaunchCommand = fmt.Sprintf("kitsoki run %s --warp %s", quoteArg(filepath.Join(receipt.AppPath, "app.yaml")), quoteArg(receipt.LaunchBasisPath))
	}
	if err := writeJSON(filepath.Join(s.OutputDir, receipt.WorkflowID, "receipt.json"), receipt); err != nil {
		return nil, err
	}
	return receipt, nil
}

// ValidateDraft validates an existing generated draft package.
func (s *Service) ValidateDraft(appPath, manifestPath string) ValidationReport {
	report := ValidationReport{}
	if _, err := app.Load(filepath.Join(appPath, "app.yaml")); err != nil {
		report.Errors = append(report.Errors, fmt.Sprintf("app invalid: %v", err))
	}
	manifest, err := readManifest(manifestPath)
	if err != nil {
		report.Errors = append(report.Errors, fmt.Sprintf("manifest invalid: %v", err))
		report.OK = false
		return report
	}
	report.Errors = append(report.Errors, validateManifest(s.RootDir, manifest, appPath)...)
	report.OK = len(report.Errors) == 0
	return report
}

// Export copies a generated workflow package to targetDir and writes starter
// flow/cassette artifacts derived from the trace when available.
func (s *Service) Export(ctx context.Context, workflowID string, req ExportRequest) (*Receipt, error) {
	_ = ctx
	s.ensure()
	draftDir := filepath.Join(s.OutputDir, workflowID)
	receipt, err := s.ReadReceipt(workflowID)
	if err != nil {
		return nil, err
	}
	if !receipt.Validation.OK {
		receipt.Validation = s.ValidateDraft(receipt.AppPath, receipt.ManifestPath)
		if !receipt.Validation.OK {
			return nil, fmt.Errorf("dynamicworkflow: workflow %s is not validated", receipt.WorkflowID)
		}
	}
	targetDir := req.TargetDir
	if targetDir == "" {
		targetDir = filepath.Join(s.RootDir, "stories", receipt.Slug)
	}
	if isBaseStoryPath(targetDir) && !req.AllowBaseStory {
		return nil, fmt.Errorf("dynamicworkflow: base-story export to %s requires explicit approval", targetDir)
	}
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return nil, fmt.Errorf("dynamicworkflow: create export dir: %w", err)
	}
	exportAppDir := filepath.Join(targetDir, "app")
	if err := copyDir(filepath.Join(draftDir, "app"), exportAppDir); err != nil {
		return nil, err
	}
	manifest, err := readManifest(filepath.Join(draftDir, "manifest.yaml"))
	if err != nil {
		return nil, err
	}
	exportAppPath := filepath.Join(exportAppDir, "app.yaml")
	manifest.Defaults.TraceRoot = filepath.ToSlash(filepath.Join(targetDir, "traces"))
	for i := range manifest.Items {
		manifest.Items[i].Story = filepath.ToSlash(exportAppPath)
		manifest.Items[i].ImplementationStory = filepath.ToSlash(exportAppPath)
		for j := range manifest.Items[i].Verify {
			switch manifest.Items[i].Verify[j].Kind {
			case "story_validate", "story_test":
				manifest.Items[i].Verify[j].Story = filepath.ToSlash(exportAppPath)
			}
		}
	}
	if err := writeYAML(filepath.Join(targetDir, "manifest.yaml"), manifest); err != nil {
		return nil, err
	}
	if err := writeLaunchBasis(filepath.Join(targetDir, "launch.yaml"), filepath.Join(targetDir, "manifest.yaml")); err != nil {
		return nil, err
	}
	readme := strings.TrimSpace(fmt.Sprintf(`# %s

Exported from dynamic workflow %s.

Source trace: %s
Validation: %t
`, receipt.Slug, workflowID, receipt.TracePath, receipt.Validation.OK)) + "\n"
	if err := os.WriteFile(filepath.Join(targetDir, "README.md"), []byte(readme), 0o644); err != nil {
		return nil, err
	}
	report := ExportReport{
		WorkflowID: workflowID,
		ExportPath: targetDir,
		Status:     "copied",
		BaseStory:  isBaseStoryPath(targetDir),
		Artifacts: []string{
			filepath.ToSlash(filepath.Join(targetDir, "app", "app.yaml")),
			filepath.ToSlash(filepath.Join(targetDir, "manifest.yaml")),
			filepath.ToSlash(filepath.Join(targetDir, "launch.yaml")),
			filepath.ToSlash(filepath.Join(targetDir, "README.md")),
		},
	}
	if tracePath := receipt.TracePath; tracePath != "" {
		flowRes, convErr := testrunner.ConvertTraceToFlow(tracePath, testrunner.ConvertOptions{
			AppPath:      filepath.ToSlash(filepath.Join(targetDir, "app", "app.yaml")),
			CassettePath: filepath.ToSlash(filepath.Join(targetDir, "flows", "generated.cassette.yaml")),
		})
		if convErr != nil {
			report.Status = "copied-with-todos"
			report.Warnings = append(report.Warnings, convErr.Error())
			report.Todos = append(report.Todos, "review the trace and produce a starter flow by hand")
			flowsDir := filepath.Join(targetDir, "flows")
			if err := os.MkdirAll(flowsDir, 0o755); err != nil {
				return nil, err
			}
			flowPath := filepath.Join(flowsDir, "generated.yaml")
			if err := writeYAML(flowPath, map[string]any{
				"test_kind":     "flow",
				"app":           filepath.ToSlash(filepath.Join(targetDir, "app", "app.yaml")),
				"initial_state": "idle",
				"initial_world": map[string]any{
					"manifest_path": filepath.ToSlash(filepath.Join(targetDir, "manifest.yaml")),
				},
				"turns": []any{},
			}); err != nil {
				return nil, err
			}
			report.StarterFlowPath = filepath.ToSlash(flowPath)
			report.Artifacts = append(report.Artifacts, filepath.ToSlash(flowPath))
		} else {
			flowsDir := filepath.Join(targetDir, "flows")
			if err := os.MkdirAll(flowsDir, 0o755); err != nil {
				return nil, err
			}
			flowPath := filepath.Join(flowsDir, "generated.yaml")
			if err := os.WriteFile(flowPath, flowRes.FlowYAML, 0o644); err != nil {
				return nil, err
			}
			report.StarterFlowPath = filepath.ToSlash(flowPath)
			report.Artifacts = append(report.Artifacts, filepath.ToSlash(flowPath))
			if len(flowRes.CassetteYAML) > 0 {
				cassettePath := filepath.Join(flowsDir, "generated.cassette.yaml")
				if err := os.WriteFile(cassettePath, flowRes.CassetteYAML, 0o644); err != nil {
					return nil, err
				}
				report.StarterCassette = filepath.ToSlash(cassettePath)
				report.Artifacts = append(report.Artifacts, filepath.ToSlash(cassettePath))
			}
			report.Todos = append(report.Todos, fmt.Sprintf("review the starter flow at %s", report.StarterFlowPath))
			if report.StarterCassette == "" {
				report.Todos = append(report.Todos, "add a host cassette if the trace recorded host calls")
			}
		}
	} else {
		report.Status = "copied-with-todos"
		report.Todos = append(report.Todos, "attach a trace before expecting starter flow/cassette export")
		flowsDir := filepath.Join(targetDir, "flows")
		if err := os.MkdirAll(flowsDir, 0o755); err != nil {
			return nil, err
		}
		flowPath := filepath.Join(flowsDir, "generated.yaml")
		if err := writeYAML(flowPath, map[string]any{
			"test_kind":     "flow",
			"app":           filepath.ToSlash(filepath.Join(targetDir, "app", "app.yaml")),
			"initial_state": "idle",
			"initial_world": map[string]any{
				"manifest_path": filepath.ToSlash(filepath.Join(targetDir, "manifest.yaml")),
			},
			"turns": []any{},
		}); err != nil {
			return nil, err
		}
		report.StarterFlowPath = filepath.ToSlash(flowPath)
		report.Artifacts = append(report.Artifacts, filepath.ToSlash(flowPath))
	}
	reportPath := filepath.Join(targetDir, "export-report.json")
	if err := writeJSON(reportPath, report); err != nil {
		return nil, err
	}
	receipt.ExportPath = targetDir
	receipt.ExportReportPath = reportPath
	receipt.LaunchBasisPath = filepath.Join(targetDir, "launch.yaml")
	receipt.AppPath = exportAppDir
	receipt.ManifestPath = filepath.Join(targetDir, "manifest.yaml")
	receipt.LaunchCommand = fmt.Sprintf("kitsoki run %s --warp %s", quoteArg(filepath.Join(exportAppDir, "app.yaml")), quoteArg(receipt.LaunchBasisPath))
	if err := writeJSON(filepath.Join(draftDir, "receipt.json"), receipt); err != nil {
		return nil, err
	}
	if err := appendWorkflowEvent(receipt.EventsPath, map[string]any{
		"kind":         "dynamic.workflow.exported",
		"workflow_id":  workflowID,
		"at":           s.nowUTC(),
		"target_dir":   targetDir,
		"report_path":  reportPath,
		"receipt_path": filepath.Join(draftDir, "receipt.json"),
		"receipt_hash": mustHashFile(filepath.Join(draftDir, "receipt.json")),
		"artifacts":    report.Artifacts,
	}); err != nil {
		return nil, err
	}
	return receipt, nil
}

// ReadReceipt loads receipt.json for a draft.
func (s *Service) ReadReceipt(workflowID string) (*Receipt, error) {
	s.ensure()
	path := filepath.Join(s.OutputDir, workflowID, "receipt.json")
	var receipt Receipt
	if err := readJSON(path, &receipt); err != nil {
		return nil, err
	}
	return &receipt, nil
}

func (s *Service) buildManifest(req GenerateRequest, workflowID, appPath, manifestPath string) Manifest {
	goal := strings.TrimSpace(req.Goal)
	if goal == "" {
		goal = workflowID
	}
	goalSentence := truncateWords(goal, 12)
	steps := []struct {
		id     string
		title  string
		prompt string
		verify []ManifestVerify
	}{
		{
			id:     "scope",
			title:  "Scope the task",
			prompt: fmt.Sprintf("Read the goal carefully and identify the parts that need implementation for %s.", goalSentence),
			verify: []ManifestVerify{{Kind: "story_validate", Story: filepath.ToSlash(filepath.Join(appPath, "app.yaml"))}},
		},
		{
			id:     "implement",
			title:  "Implement the core slice",
			prompt: fmt.Sprintf("Make the smallest coherent implementation for %s and keep the result reviewable.", goalSentence),
			verify: []ManifestVerify{{Kind: "story_validate", Story: filepath.ToSlash(filepath.Join(appPath, "app.yaml"))}},
		},
		{
			id:     "wire",
			title:  "Wire the surfaces",
			prompt: fmt.Sprintf("Thread the result through the MCP, CLI, and runstatus-facing surfaces for %s.", goalSentence),
			verify: []ManifestVerify{{Kind: "story_validate", Story: filepath.ToSlash(filepath.Join(appPath, "app.yaml"))}},
		},
		{
			id:     "test",
			title:  "Test and document it",
			prompt: fmt.Sprintf("Add deterministic checks, docs, and dogfood evidence for %s.", goalSentence),
			verify: []ManifestVerify{
				{Kind: "story_validate", Story: filepath.ToSlash(filepath.Join(appPath, "app.yaml"))},
				{Kind: "command", Cmd: "go test ./..."},
			},
		},
	}
	items := make([]ManifestItem, 0, len(steps))
	for i, step := range steps {
		items = append(items, ManifestItem{
			ID:                   step.id,
			Title:                step.title,
			Priority:             i + 1,
			Story:                filepath.ToSlash(filepath.Join(appPath, "app.yaml")),
			Mode:                 "drive",
			Prompt:               step.prompt,
			ImplementationStory:  filepath.ToSlash(filepath.Join(appPath, "app.yaml")),
			ImplementationPrompt: step.prompt,
			GateCommand:          "",
			Verify:               step.verify,
		})
	}
	return Manifest{
		Version: ManifestVersion,
		Defaults: ManifestDefaults{
			Harness:           "live",
			Profile:           "codex-native",
			Model:             "gpt-5.5",
			TraceRoot:         filepath.ToSlash(filepath.Join(filepath.Dir(manifestPath), "traces")),
			RequireTraceModel: true,
		},
		Items: items,
	}
}

func validateManifest(root string, manifest Manifest, appPath string) []string {
	var errs []string
	if manifest.Version != ManifestVersion {
		errs = append(errs, "version must be punch-list/v1")
	}
	if len(manifest.Items) == 0 {
		errs = append(errs, "items must be a non-empty list")
	}
	seen := map[string]bool{}
	for i, item := range manifest.Items {
		prefix := fmt.Sprintf("items[%d]", i)
		if strings.TrimSpace(item.ID) == "" {
			errs = append(errs, prefix+".id is required")
		}
		if seen[item.ID] {
			errs = append(errs, "duplicate item id: "+item.ID)
		}
		seen[item.ID] = true
		if !pathExists(root, item.Story) {
			errs = append(errs, fmt.Sprintf("%s.story path does not exist: %s", prefix, item.Story))
		}
		if item.ImplementationStory != "" && !pathExists(root, item.ImplementationStory) {
			errs = append(errs, fmt.Sprintf("%s.implementation_story path does not exist: %s", prefix, item.ImplementationStory))
		}
		if len(item.Verify) == 0 {
			errs = append(errs, fmt.Sprintf("%s.verify must not be empty", prefix))
		}
		for j, check := range item.Verify {
			checkPrefix := fmt.Sprintf("%s.verify[%d]", prefix, j)
			switch check.Kind {
			case "story_validate", "story_test":
				if !pathExists(root, check.Story) {
					errs = append(errs, fmt.Sprintf("%s.story path does not exist: %s", checkPrefix, check.Story))
				}
			case "command":
				if isLLMSpendingCommand(check.Cmd) {
					errs = append(errs, fmt.Sprintf("%s.cmd appears to invoke an LLM or live run", checkPrefix))
				}
			default:
				errs = append(errs, fmt.Sprintf("%s.kind is unsupported: %s", checkPrefix, check.Kind))
			}
		}
	}
	_ = appPath
	return errs
}

func readManifest(path string) (Manifest, error) {
	var m Manifest
	b, err := os.ReadFile(path)
	if err != nil {
		return m, err
	}
	if err := goyaml.Unmarshal(b, &m); err != nil {
		return m, err
	}
	return m, nil
}

func writeLaunchBasis(path, manifestPath string) error {
	body := map[string]any{
		"state": "idle",
		"world": map[string]any{
			"manifest_path": filepath.ToSlash(manifestPath),
		},
	}
	return writeYAML(path, body)
}

func writeYAML(path string, v any) error {
	b, err := goyaml.Marshal(v)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}

func writeJSON(path string, v any) error {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, append(b, '\n'), 0o644)
}

func appendWorkflowEvent(path string, v any) error {
	if path == "" {
		return nil
	}
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	b = append(b, '\n')
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	_, err = f.Write(b)
	return err
}

// AppendWorkflowEvent writes one dynamic-workflow lifecycle event to the
// draft's JSONL event log.
func AppendWorkflowEvent(path string, v any) error { return appendWorkflowEvent(path, v) }

func mustHashFile(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	sum := sha256.Sum256(b)
	return "sha256:" + hex.EncodeToString(sum[:])
}

// HashFile returns a stable sha256 digest of path's bytes, or "" when the file
// cannot be read.
func HashFile(path string) string { return mustHashFile(path) }

func (s *Service) nowUTC() time.Time {
	if s.Now == nil {
		return time.Now().UTC()
	}
	return s.Now().UTC()
}

func readJSON(path string, v any) error {
	b, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(b, v)
}

func pathExists(root, rel string) bool {
	if rel == "" {
		return false
	}
	if filepath.IsAbs(rel) {
		_, err := os.Stat(rel)
		return err == nil
	}
	_, err := os.Stat(filepath.Join(root, filepath.FromSlash(rel)))
	return err == nil
}

func copyDir(src, dst string) error {
	return filepath.WalkDir(src, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, relErr := filepath.Rel(src, path)
		if relErr != nil {
			return relErr
		}
		target := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		return copyFile(path, target)
	})
}

func copyFile(src, dst string) error {
	b, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dst, b, 0o644)
}

func workflowSlug(slug, goal string) string {
	if s := strings.TrimSpace(slug); s != "" {
		return sanitizeSlug(s)
	}
	return sanitizeSlug(goal)
}

func sanitizeSlug(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = strings.ReplaceAll(s, " ", "-")
	s = unsafeSlug.ReplaceAllString(s, "-")
	s = strings.Trim(s, "-_.")
	if s == "" {
		return "workflow"
	}
	return s
}

func truncateWords(s string, max int) string {
	if max <= 0 {
		return strings.TrimSpace(s)
	}
	parts := strings.Fields(strings.TrimSpace(s))
	if len(parts) <= max {
		return strings.Join(parts, " ")
	}
	return strings.Join(parts[:max], " ") + " ..."
}

func quoteArg(s string) string {
	if s == "" {
		return "''"
	}
	if strings.ContainsAny(s, " \t\n'\"") {
		return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
	}
	return s
}

func isLLMSpendingCommand(cmd string) bool {
	lowered := strings.ToLower(strings.TrimSpace(cmd))
	if lowered == "" {
		return false
	}
	patterns := []string{"claude", "codex", "openai", "anthropic", "kitsoki tour", "harness: live", "--harness live"}
	for _, p := range patterns {
		if strings.Contains(lowered, p) {
			return true
		}
	}
	return false
}

func isBaseStoryPath(target string) bool {
	if target == "" {
		return false
	}
	clean := filepath.ToSlash(filepath.Clean(target))
	return strings.Contains(clean, "/internal/basestories/stories/") || strings.HasPrefix(clean, "internal/basestories/stories/")
}

// MarshalReceipt is a convenience helper for callers that want a stable JSON
// string without re-declaring the encode options.
func MarshalReceipt(r *Receipt) (string, error) {
	b, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return "", err
	}
	return string(b), nil
}

// WriteReceipt writes a receipt to disk.
func WriteReceipt(path string, r *Receipt) error {
	return writeJSON(path, r)
}

// CopyTemplateTree copies the template story tree into dst.
func CopyTemplateTree(dst string) error {
	if dst == "" {
		return fmt.Errorf("dynamicworkflow: dst is required")
	}
	return copyDir(filepath.Clean(DefaultTemplateStoryDir), dst)
}

// ReadFile is a small test seam for callers that need bytes from a generated
// artifact without duplicating os.ReadFile in tests.
func ReadFile(path string) ([]byte, error) { return os.ReadFile(path) }
