#!/usr/bin/env bash
# run_cell.sh — orchestrate ONE bake-off grid cell: prepare its worktree, run
# the candidate under the treatment, time it (wall seconds), capture the
# transcript, and write a sidecar JSON that score.py consumes. It does NOT score
# (scoring is score.py, run separately — the oracle test stays out of the tree).
#
#   Usage: run_cell.sh <bug-id> <candidate-key> <treatment> [guidance-message]
#   Example: run_cell.sh bug1 opus-4.8 single
#            run_cell.sh bug1 opus-4.8 single "the test is still RED — look at runOnEnter ordering"
#
# ┌─────────────────────────────────────────────────────────────────────────┐
# │ COST WARNING. This is the ONLY cost-bearing piece of the bake-off.        │
# │ The treatment branches below invoke REAL LLMs (claude -p / the kitsoki    │
# │ live harness). It is run MANUALLY by the operator, NEVER in CI and NEVER  │
# │ automatically. prepare.sh / score.py / aggregate.py are all free.         │
# └─────────────────────────────────────────────────────────────────────────┘
#
# Behavior is dispatched by (treatment, candidate.invoker), read from
# bakeoff.yaml:
#
#   treatment=single, invoker=claude_p  → scripted here: `claude -p` + a
#       resumable, operator-driven guidance loop (this file runs the turns).
#   treatment=single, invoker=session   → NO profile-pinned single-turn CLI
#       exists (verified: `kitsoki agent task` has no --profile/--model; the
#       only profile-selecting headless seam is the studio MCP session_new).
#       So this prints the exact MCP/operator procedure + where the trace lands.
#   treatment=kitsoki (all candidates)  → driving stories/bugfix is studio-MCP /
#       operator-driven. Prints the exact session_new args + a trace-locate
#       helper afterward (reports trace_found=false clearly — itself a finding).
#
# Sidecar (consumed by score.py):
#   results/sidecars/<bug>-<candidate>-<treatment>.env  (+ .json mirror)
#     wall_time_s, guidance_turns, transcript_path, session_id, trace_found
set -euo pipefail

usage() {
  echo "usage: $(basename "$0") <bug-id> <candidate-key> <treatment> [guidance-message]" >&2
  echo "  treatments: single | kitsoki" >&2
  exit 2
}
# --locate <bug> <cand> <treatment>: trace-locate helper for kitsoki cells.
# Detected here so it bypasses worktree-prepare + manifest dispatch entirely.
MODE="run"
if [ "${1:-}" = "--locate" ]; then
  MODE="locate"; shift
fi
# Defaulted so write_sidecar is safe under `set -u` in --locate mode (where the
# manifest-derived candidate fields are not parsed).
INVOKER=""; PROFILE=""; MODEL=""; EFFORT=""; WT_PATH=""
[ $# -ge 3 ] || usage
BUG="$1"; CAND="$2"; TREAT="$3"; GUIDANCE="${4:-}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/bakeoff.yaml"
REPO_ROOT="$(cd "$SCRIPT_DIR" && git rev-parse --show-toplevel)"
PROMPT_FILE="$SCRIPT_DIR/prompts/${BUG}.md"
SIDECAR_DIR="$SCRIPT_DIR/results/sidecars"
mkdir -p "$SIDECAR_DIR"
SIDECAR="$SIDECAR_DIR/${BUG}-${CAND}-${TREAT}.env"

# --- manifest helpers -------------------------------------------------------
bug_field()  { python3 - "$MANIFEST" "$BUG"  "$1" bugs id <<'PY'
import sys, yaml
m,key,field,sect,idkey=sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5]
d=yaml.safe_load(open(m))
for r in d.get(sect,[]):
    if r.get(idkey)==key: print(r.get(field,"")); break
PY
}
cand_field() { python3 - "$MANIFEST" "$CAND" "$1" candidates key <<'PY'
import sys, yaml
m,key,field,sect,idkey=sys.argv[1],sys.argv[2],sys.argv[3],sys.argv[4],sys.argv[5]
d=yaml.safe_load(open(m))
for r in d.get(sect,[]):
    if r.get(idkey)==key: print(r.get(field,"")); break
PY
}
run_field()  { python3 - "$MANIFEST" "$1" <<'PY'
import sys, yaml
print(yaml.safe_load(open(sys.argv[1])).get("run",{}).get(sys.argv[2],""))
PY
}

if [ "$MODE" = "run" ]; then
  INVOKER="$(cand_field invoker)"
  PROFILE="$(cand_field profile)"
  MODEL="$(cand_field model)"
  EFFORT="$(cand_field effort)"
  TICKET="$(bug_field ticket)"
  TITLE="$(bug_field title)"
  MAX_TURNS="$(run_field max_guidance_turns)"; MAX_TURNS="${MAX_TURNS:-5}"
  STORY="$(run_field story)"; STORY="${STORY:-stories/bugfix/app.yaml}"

  [ -n "$INVOKER" ] || { echo "run_cell: unknown candidate '$CAND'" >&2; exit 1; }

  # --- prepare the (isolated) worktree -------------------------------------
  WT_PATH="$("$SCRIPT_DIR/prepare.sh" "$BUG" "$CAND" "$TREAT")"
  echo "run_cell: worktree = $WT_PATH" >&2
fi

# --- sidecar writer ---------------------------------------------------------
# Re-runnable: each invocation rewrites the sidecar. guidance_turns is read back
# from the existing sidecar so resumed guidance turns accumulate.
prev_turns() { [ -f "$SIDECAR" ] && (grep -E '^guidance_turns=' "$SIDECAR" | cut -d= -f2) || echo 0; }
write_sidecar() {  # write_sidecar <wall_s> <turns> <transcript> <session> <trace_found>
  cat > "$SIDECAR" <<EOF
# bake-off cell sidecar — generated by run_cell.sh; consumed by score.py
bug=$BUG
candidate=$CAND
treatment=$TREAT
invoker=$INVOKER
profile=$PROFILE
model=$MODEL
effort=$EFFORT
worktree=$WT_PATH
wall_time_s=$1
guidance_turns=$2
transcript_path=$3
session_id=$4
trace_found=$5
EOF
  # JSON mirror for tools that prefer it.
  python3 - "$SIDECAR" "${SIDECAR%.env}.json" <<'PY'
import sys
env,out=sys.argv[1],sys.argv[2]
d={}
for line in open(env):
    line=line.strip()
    if not line or line.startswith("#") or "=" not in line: continue
    k,v=line.split("=",1); d[k]=v
import json; json.dump(d, open(out,"w"), indent=2)
PY
  echo "run_cell: sidecar -> $SIDECAR" >&2
}

# Resolve the Claude Code transcript path for a session in a given CWD.
# Claude writes ~/.claude/projects/<encoded-cwd>/<session>.jsonl, where the
# encoding replaces '/' (and '.') with '-'.
resolve_claude_transcript() {  # resolve_claude_transcript <cwd> <session_id>
  local cwd="$1" sid="$2"
  local enc; enc="$(printf '%s' "$cwd" | sed 's/[/.]/-/g')"
  local f="$HOME/.claude/projects/$enc/$sid.jsonl"
  if [ -f "$f" ]; then printf '%s' "$f"; return 0; fi
  # Fallback: newest jsonl mentioning the session id anywhere under projects/.
  f="$(grep -rl "$sid" "$HOME/.claude/projects/" 2>/dev/null | head -1 || true)"
  printf '%s' "$f"
}

############################################################################
# treatment=single, invoker=claude_p  — the only fully-scripted, cost-bearing
# branch. First call runs the prompt; pass a guidance message to resume.
############################################################################
run_single_claude_p() {
  local sid_file="$SIDECAR_DIR/${BUG}-${CAND}-${TREAT}.session"
  [ -f "$PROMPT_FILE" ] || { echo "run_cell: missing prompt $PROMPT_FILE" >&2; exit 1; }

  local start end wall sid out turns
  start="$(date +%s)"

  if [ -z "$GUIDANCE" ]; then
    # ── turn 1: the staged prompt ──
    echo "run_cell: [COST] claude -p turn 1 (model=$MODEL) in $WT_PATH" >&2
    out="$(cd "$WT_PATH" && claude -p "$(cat "$PROMPT_FILE")" \
            --output-format json --model "$MODEL")"
    turns=1
  else
    # ── resumed guidance turn (operator-decided after an oracle check) ──
    [ -f "$sid_file" ] || { echo "run_cell: no prior session to --resume (run turn 1 first)" >&2; exit 1; }
    sid="$(cat "$sid_file")"
    local n; n="$(prev_turns)"
    [ "$n" -lt "$MAX_TURNS" ] || { echo "run_cell: max_guidance_turns=$MAX_TURNS reached" >&2; exit 1; }
    echo "run_cell: [COST] claude -p --resume $sid guidance turn $((n+1))" >&2
    out="$(cd "$WT_PATH" && claude -p --resume "$sid" "$GUIDANCE" \
            --output-format json --model "$MODEL")"
    turns=$((n+1))
  fi

  end="$(date +%s)"; wall=$((end-start))
  # Add this turn's wall to any prior wall (resumed turns accumulate).
  if [ -f "$SIDECAR" ]; then
    local pw; pw="$(grep -E '^wall_time_s=' "$SIDECAR" | cut -d= -f2 || echo 0)"
    wall=$((wall + ${pw:-0}))
  fi

  sid="$(printf '%s' "$out" | python3 -c 'import sys,json; print(json.load(sys.stdin).get("session_id",""))' 2>/dev/null || true)"
  [ -n "$sid" ] && printf '%s' "$sid" > "$sid_file"

  local transcript; transcript="$(resolve_claude_transcript "$WT_PATH" "$sid")"
  write_sidecar "$wall" "$turns" "$transcript" "$sid" "true"

  cat <<EOF >&2

────────────────────────────────────────────────────────────────────────────
 OPERATOR: oracle check (decide if a guidance turn is warranted; max $MAX_TURNS)
   The oracle test is NOT in this tree. Score with score.py, which copies it in.
   Quick read on whether the candidate is on track (run from the worktree):

     cd "$WT_PATH" && git diff --stat && go build ./... 2>&1 | tail

   To drive a guidance turn (resumes the same session):

     "$0" $BUG $CAND $TREAT "your guidance message here"
────────────────────────────────────────────────────────────────────────────
EOF
}

############################################################################
# treatment=single, invoker=session  — NO profile-pinned single-turn CLI.
# `kitsoki agent task` exists and is headless but takes NO --profile/--model
# (profile is config-driven; the agent's model lives on the agent-def). The
# only headless seam that selects a profile is the studio MCP session_new.
# So we prepare everything and print the exact operator/MCP procedure.
############################################################################
print_single_session_procedure() {
  local trace="$REPO_ROOT/.worktrees/.bakeoff-traces/${BUG}-${CAND}-${TREAT}.jsonl"
  mkdir -p "$(dirname "$trace")"
  cat <<EOF
────────────────────────────────────────────────────────────────────────────
 single / session-invoker cell: $BUG · $CAND  (profile=$PROFILE model=$MODEL)

 There is NO profile-pinned single-turn kitsoki CLI (verified: \`kitsoki agent
 task\` has no --profile/--model; profile is config-driven). Drive the single
 staged prompt through the studio MCP under this candidate's profile.

 Operator/MCP steps (run via kitsoki studio MCP, e.g. mcp__kitsoki__*):

  1. Ensure profile '$PROFILE' (model '$MODEL') is configured in .kitsoki.local.yaml.
  2. session_new {
       story_path: "$STORY",          # or a thin single-prompt story; see README
       harness:    "live",
       profile:    "$PROFILE",
       trace:      "$trace"
     }
  3. session_drive { handle, input: "\$(cat $PROMPT_FILE)" }
     …iterate up to $MAX_TURNS guidance turns, deciding each via the oracle check.
  4. Trace lands at:  $trace
     (and journaled under ~/.kitsoki/sessions/ — see the locate helper below).

 After the drive, capture timing + path into the sidecar by hand or re-run:
     "$0" $BUG $CAND $TREAT     (then edit $SIDECAR if needed)
────────────────────────────────────────────────────────────────────────────
EOF
  # Seed a sidecar shell so score.py finds the cell even before manual fill-in.
  write_sidecar "0" "0" "$trace" "" "$([ -f "$trace" ] && echo true || echo false)"
}

############################################################################
# treatment=kitsoki (all candidates) — drive stories/bugfix under the candidate.
# Studio-MCP / operator-driven. Print exact session_new args (with the ticket
# seeded into initial_world) + a trace-locate helper afterward.
#
# KNOWN OPEN BUG: MCP-driven bugfix sessions may NOT leave a discoverable local
# trace. The locate helper must report trace_found=false clearly — that absence
# is itself a study finding, not a script failure.
############################################################################
print_kitsoki_procedure() {
  # Seed the bug ticket into the candidate's workdir so the pipeline's ticket
  # loader can read it (the pipeline expects a ticket on disk / in world).
  local seeded="$WT_PATH/$TICKET"
  if [ -f "$REPO_ROOT/$TICKET" ] && [ ! -f "$seeded" ]; then
    mkdir -p "$(dirname "$seeded")"
    cp "$REPO_ROOT/$TICKET" "$seeded"
    echo "run_cell: seeded ticket -> $seeded" >&2
  fi

  cat <<EOF
────────────────────────────────────────────────────────────────────────────
 kitsoki cell: $BUG · $CAND  (profile=$PROFILE model=$MODEL effort=$EFFORT)

 Drive stories/bugfix under this candidate via the studio MCP (operator/agent-
 driven; not pure bash). Exact session_new arguments:

  session_new {
    story_path:   "$STORY",
    harness:      "live",
    profile:      "$PROFILE",
    initial_world: {
      ticket_id:    "$BUG",
      ticket_title: "$TITLE",
      thread:       "$BUG",
      workdir:      "$WT_PATH",
      base_branch:  "main",
      bugfix_mode:  "full",
      judge_mode:   "human"
    }
  }

  Then drive the pipeline (start → accept → … ) per stories/bugfix. The maker
  model is set on the story agent-def, NOT the profile — to pin '$MODEL', edit
  stories/bugfix agents.maker.model before driving (see MEMORY: maker-model-on-agent-def).

 After it finishes, locate the trace + wall time:
     "$0" --locate $BUG $CAND $TREAT
────────────────────────────────────────────────────────────────────────────
EOF
  write_sidecar "0" "0" "" "" "false"
}

# Trace-locate helper for kitsoki cells: find the newest bugfix session whose
# trace mentions this bug/worktree, capture path + wall time. Reports clearly
# when none is found (trace_found=false — a known-bug finding, not an error).
locate_kitsoki_trace() {
  local sdir="$HOME/.kitsoki/sessions/bugfix"
  local found="" wall="0"
  if [ -d "$sdir" ]; then
    # Newest .jsonl mentioning the bug id or worktree path.
    found="$(grep -rl -e "$BUG" -e "$WT_PATH" "$sdir" 2>/dev/null \
              | xargs -r ls -t 2>/dev/null | head -1 || true)"
  fi
  if [ -n "$found" ] && [ -f "$found" ]; then
    # Wall time from first→last event timestamp if present, else file mtime span.
    wall="$(python3 - "$found" <<'PY' 2>/dev/null || echo 0
import sys, json
ts=[]
for line in open(sys.argv[1]):
    try:
        o=json.loads(line)
    except Exception:
        continue
    for k in ("ts","timestamp","time","at"):
        if k in o:
            ts.append(o[k]); break
print(0 if len(ts)<2 else "")  # numeric span hard to trust across formats; leave 0
PY
)"
    write_sidecar "${wall:-0}" "0" "$found" "" "true"
    echo "run_cell: located trace -> $found (trace_found=true)" >&2
  else
    write_sidecar "0" "0" "" "" "false"
    echo "run_cell: NO local trace found under $sdir for $BUG/$CAND." >&2
    echo "          trace_found=false. This is a KNOWN open bug (MCP-driven bugfix" >&2
    echo "          sessions may not journal locally) and is itself a finding." >&2
  fi
}

# --locate shortcut: run_cell.sh --locate <bug> <cand> <treatment>
if [ "$MODE" = "locate" ]; then
  WT_PATH="$REPO_ROOT/.worktrees/bakeoff-${BUG}-${CAND}-${TREAT}"
  locate_kitsoki_trace
  exit 0
fi

# --- dispatch ---------------------------------------------------------------
case "$TREAT" in
  single)
    case "$INVOKER" in
      claude_p) run_single_claude_p ;;
      session)  print_single_session_procedure ;;
      *) echo "run_cell: unknown invoker '$INVOKER'" >&2; exit 1 ;;
    esac
    ;;
  kitsoki)
    print_kitsoki_procedure ;;
  *)
    echo "run_cell: unknown treatment '$TREAT' (single|kitsoki)" >&2; exit 1 ;;
esac
