"""Deterministic Slidey deck generation for Persona QA run bundles."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


DECK_RESOLUTION = {"width": 1920, "height": 1080}
REPO_ROOT = Path(__file__).resolve().parents[2]
PROOF_SOURCES = {"local", "retained", "external", "cassette"}
LOCAL_PROOF_SOURCES = {"local", "cassette"}
NON_PROOF_SOURCES = {"demo", "fake", "placeholder", "synthetic"}
NON_PROOF_WORDS = ("demo placeholder", "deterministic placeholder", "fake", "placeholder", "synthetic", "stub")
MIN_RRWEB_EVENTS = 20


class PlaybackEvidenceError(ValueError):
    """Raised when a manifest claims playback proof without proof provenance."""


def build_deck(
    run_dir: Path,
    *,
    title: str = "",
    max_playback_scenes: int = 6,
    source_ref: str = "",
) -> dict[str, Any]:
    """Build a stable Slidey spec from a Persona QA / product-journey run dir.

    The renderer is deliberately offline: it only reads JSON artifacts already
    present in ``run_dir`` and never records media or invokes a model. Re-running
    it over the same files produces byte-identical JSON when written with
    :func:`deck_json`.
    """

    run = _read_json(run_dir / "run.json")
    media_manifest = _read_optional_json(run_dir / "media-manifest.json", {"items": [], "summary": {}})
    outcomes = _read_optional_json(run_dir / "scenario-outcomes.json", {"items": [], "summary": {}})
    findings = _read_optional_json(run_dir / "findings.json", {"items": [], "summary": {}})
    review = _read_optional_json(run_dir / "review.json", {"status": "not_reviewed", "summary": "", "checks": []})
    metrics = _read_optional_json(run_dir / "metrics.json", {})
    driver_plan = _read_optional_json(run_dir / "driver-plan.json", {"scenarios": []})
    driver_journal = _read_optional_json(run_dir / "driver-journal.json", {"items": []})

    run_id = str(run.get("run_id", run_dir.name))
    project = _as_dict(run.get("project"))
    persona = _as_dict(run.get("persona"))
    project_label = _label(project, "Project")
    persona_label = _label(persona, "Persona")
    deck_title = title or f"{project_label} Persona QA"
    scenarios = [_as_dict(item) for item in run.get("scenarios", [])]
    playback_candidates = _playback_candidates(media_manifest)
    playback_items, blocked_playback_items = _classify_playback_items(playback_candidates, run_dir)
    playback_scenes = _playback_scenes(playback_items, max_playback_scenes=max_playback_scenes)

    scenes: list[dict[str, Any]] = [
        {
            "type": "title",
            "eyebrow": "Persona QA",
            "title": deck_title,
            "subtitle": f"{project_label} - {persona_label} - {run_id}",
            "narration": "This deck was generated deterministically from an existing Persona QA run bundle and its recorded media manifest.",
        },
        _persona_scene(persona),
        _scenario_table_scene(scenarios, outcomes, playback_items),
        _review_scene(review, metrics),
        _findings_scene(findings, outcomes),
        _media_manifest_scene(playback_items, blocked_playback_items),
    ]

    driver_scene = _driver_scene(driver_plan, driver_journal)
    if driver_scene is not None:
        scenes.append(driver_scene)
    scenes.extend(playback_scenes)
    display_run_dir = source_ref or run_dir.name
    scenes.append(_next_scene(display_run_dir, playback_scenes))

    return {
        "_comment": f"Generated by the internal Persona QA deck adapter from {display_run_dir} ({run_id}). Re-run the adapter instead of hand-editing derived scenes.",
        "meta": {
            "mode": "pitch",
            "title": deck_title,
            "resolution": DECK_RESOLUTION,
            "theme": "rose-pine-moon",
        },
        "scenes": scenes,
    }


def write_deck(deck: dict[str, Any], out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(deck_json(deck), encoding="utf-8")


def deck_json(deck: dict[str, Any]) -> str:
    return json.dumps(deck, indent=2, sort_keys=True) + "\n"


def _read_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def _read_optional_json(path: Path, fallback: dict[str, Any]) -> dict[str, Any]:
    if not path.exists():
        return fallback
    return _read_json(path)


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _label(value: dict[str, Any], fallback: str) -> str:
    return str(value.get("label") or value.get("id") or fallback)


def _first_text(value: Any, fallback: str = "") -> str:
    if isinstance(value, list):
        for item in value:
            text = _first_text(item)
            if text:
                return text
        return fallback
    if isinstance(value, dict):
        return str(value.get("text") or value.get("summary") or value.get("detail") or fallback)
    if value is None:
        return fallback
    return str(value)


def _short(value: Any, *, limit: int = 150) -> str:
    text = " ".join(str(value or "").split())
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "..."


def _short_sentence(value: Any, *, limit: int = 120) -> str:
    text = " ".join(str(value or "").split())
    if len(text) <= limit:
        return text
    for marker in [". ", "; ", ": "]:
        head = text.split(marker, 1)[0]
        if head and len(head) <= limit:
            suffix = "." if marker == ". " else ""
            return head.rstrip() + suffix
    return _short(text, limit=limit)


def _short_terms(value: Any, *, limit: int = 56, max_items: int = 2) -> str:
    terms = [str(item).strip() for item in _as_list(value) if str(item).strip()]
    if not terms:
        return ""
    shown = ", ".join(terms[:max_items])
    if len(terms) > max_items:
        shown = f"{shown}, +{len(terms) - max_items}"
    return _short(shown, limit=limit)


def _lines(items: list[str], fallback: str, *, limit: int = 12) -> str:
    cleaned = [item.strip() for item in items if item and item.strip()]
    if not cleaned:
        return fallback
    return "\n".join(cleaned[:limit])


def _persona_scene(persona: dict[str, Any]) -> dict[str, Any]:
    lens = _as_dict(persona.get("persona_lens"))
    cards = [
        ("Surface", persona.get("surface_preference", ""), lens.get("starting_surface", "")),
        ("First question", "", lens.get("first_question", "")),
        ("Evidence", "", lens.get("evidence_emphasis", "")),
        ("Risk focus", _short_terms(persona.get("risk_focus")), lens.get("escalation_trigger", "")),
        ("Finding bias", "", lens.get("finding_bias", "")),
    ]
    rendered_cards = [
        {
            "label": label,
            "sub": _short(sub, limit=56),
            "lines": [_short(detail, limit=120)] if detail else [],
            "style": "primary" if label in {"First question", "Evidence"} else "secondary",
        }
        for label, sub, detail in cards
        if sub or detail
    ][:5]
    if not rendered_cards:
        rendered_cards = [
            {
                "label": "Persona",
                "sub": _short(_label(persona, "Persona"), limit=56),
                "lines": [_short(persona.get("description", "No persona lens was recorded."), limit=120)],
                "style": "primary",
            }
        ]
    return {
        "type": "cards",
        "variant": "grid",
        "title": "Persona lens",
        "columns": 3,
        "cards": rendered_cards,
        "caption": _label(persona, "Persona"),
        "narration": "The deck keeps the persona lens visible so reviewers judge the scenario evidence from the intended point of view.",
    }


def _scenario_table_scene(scenarios: list[dict[str, Any]], outcomes: dict[str, Any], playback_items: list[dict[str, Any]]) -> dict[str, Any]:
    outcomes_by_id = {
        str(item.get("scenario", "")): _as_dict(item)
        for item in _as_list(outcomes.get("items"))
        if isinstance(item, dict)
    }
    playback_by_scenario: dict[str, int] = {}
    for item in playback_items:
        scenario = str(item.get("scenario", ""))
        playback_by_scenario[scenario] = playback_by_scenario.get(scenario, 0) + 1
    rows = []
    for scenario in sorted(scenarios, key=lambda item: str(item.get("id", ""))):
        scenario_id = str(scenario.get("id", ""))
        outcome = outcomes_by_id.get(scenario_id, {})
        present = outcome.get("present_evidence_count", "")
        required = outcome.get("required_evidence_count", "")
        evidence_ratio = f"{present}/{required}" if present != "" and required != "" else str(scenario.get("evidence_status", "planned"))
        rows.append(
            {
                "cells": [
                    scenario_id,
                    str(scenario.get("stage", "")),
                    str(outcome.get("outcome") or scenario.get("status") or "planned"),
                    evidence_ratio,
                    str(playback_by_scenario.get(scenario_id, 0)),
                ]
            }
        )
    if not rows:
        rows.append({"cells": ["none", "", "not_started", "0/0", "0"]})
    return {
        "type": "table",
        "variant": "scorecard",
        "title": "Recorded scenarios",
        "columns": ["Scenario", "Stage", "Outcome", "Evidence", "Playback"],
        "rows": rows[:10],
        "caption": "Rows are sorted by scenario id for deterministic output.",
        "narration": "The scenario table ties each natural-use task to its outcome, evidence coverage, and playback count.",
    }


def _review_scene(review: dict[str, Any], metrics: dict[str, Any]) -> dict[str, Any]:
    checks = sorted(
        [item for item in _as_list(review.get("checks")) if isinstance(item, dict)],
        key=lambda item: (str(item.get("status", "")), str(item.get("id", ""))),
    )
    ready_status = "done" if str(review.get("status", "")).startswith("ready") else "pending"
    metric_detail = (
        f"{metrics.get('scenario_count', '?')} scenarios, "
        f"evidence {metrics.get('present_evidence_count', '?')}/{metrics.get('required_evidence_count', '?')}, "
        f"proof {metrics.get('proof_evidence_count', '?')}"
    )
    items = [
        {
            "label": str(review.get("status") or "not reviewed"),
            "status": ready_status,
            "detail": _short_sentence(review.get("summary") or "No review summary was recorded.", limit=126),
        },
        {
            "label": "Evidence coverage",
            "status": "done" if metrics.get("missing_evidence_count", 0) in {0, ""} else "issue",
            "detail": metric_detail,
        },
    ]
    items.extend(
        {
            "label": str(item.get("id", "check")),
            "status": _objective_status(str(item.get("status", "pending"))),
            "detail": _short_sentence(item.get("summary", ""), limit=118),
        }
        for item in checks[:3]
    )
    return {
        "type": "objectives",
        "title": "Review gate",
        "items": items[:5],
        "caption": "Bundle readiness, evidence coverage, and the highest-signal checks.",
        "narration": "The review scene summarizes bundle readiness without rerunning capture or model work.",
    }


def _findings_scene(findings: dict[str, Any], outcomes: dict[str, Any]) -> dict[str, Any]:
    cards = []
    summary = _as_dict(findings.get("summary"))
    if summary:
        cards.extend(
            {
                "label": kind,
                "sub": str(summary.get(kind, 0)),
                "lines": [f"{kind} findings recorded"],
                "style": "primary" if kind in {"strength", "fix"} else "secondary",
            }
            for kind in ["strength", "weakness", "issue", "fix", "blocked"]
        )
    else:
        counts: dict[str, int] = {}
        for item in _as_list(findings.get("items")):
            if isinstance(item, dict):
                kind = str(item.get("kind", "finding"))
                counts[kind] = counts.get(kind, 0) + 1
        cards.extend(
            {
                "label": kind,
                "sub": str(count),
                "lines": [f"{kind} findings recorded"],
                "style": "primary" if kind in {"strength", "fix"} else "secondary",
            }
            for kind, count in sorted(counts.items())
        )
    if not cards:
        cards = [{"label": "findings", "sub": "0", "lines": ["No findings were recorded."], "style": "secondary"}]

    outcome_lines = [
        f"{item.get('scenario', '')}: {item.get('outcome', '')}"
        for item in _as_list(outcomes.get("items"))
        if isinstance(item, dict)
    ]
    return {
        "type": "cards",
        "variant": "grid",
        "title": "Persona judgement",
        "cards": cards[:6],
        "caption": _lines(outcome_lines, "No scenario outcome matrix was recorded.", limit=6),
        "narration": "Findings are grouped by type so a technical reviewer can separate strengths from product risks.",
    }


def _media_manifest_scene(playback_items: list[dict[str, Any]], blocked_items: list[dict[str, Any]]) -> dict[str, Any]:
    all_items = playback_items + blocked_items
    scenarios = sorted({str(item.get("scenario", "")) for item in all_items if item.get("scenario")})
    scenario_summary = ", ".join(scenarios[:3])
    if len(scenarios) > 3:
        scenario_summary = f"{scenario_summary}, +{len(scenarios) - 3}"
    caption = _lines(
        [
            f"Verified playback: {len(playback_items)}",
            f"Blocked/unverified: {len(blocked_items)}",
            f"Videos: {sum(1 for item in playback_items if item.get('media_kind') == 'video')}",
            f"Images: {sum(1 for item in playback_items if item.get('media_kind') == 'image')}",
            f"Scenarios: {scenario_summary}" if scenario_summary else "",
        ],
        "No proof-grade playback media has been attached yet.",
    )
    items = [
        {
            "label": str(item.get("scenario", "media")),
            "status": _slidey_status(str(item.get("status", "validated"))),
            "detail": _short(item.get("notes") or item.get("path", ""), limit=120),
            "refType": "artifact",
            "ref": str(item.get("path", "")),
        }
        for item in playback_items[:4]
    ]
    remaining = max(0, 4 - len(items))
    items.extend(
        {
            "label": str(item.get("scenario", "media")),
            "status": "blocked",
            "detail": _short(item.get("notes") or item.get("proof_reason") or "Playback candidate is not proof-grade.", limit=120),
            "refType": "path",
            "ref": str(item.get("path") or "media-manifest.json"),
        }
        for item in blocked_items[:remaining]
    )
    return {
        "type": "evidence",
        "title": "Playback manifest",
        "items": items
        or [
            {
                "label": "playback",
                "status": "blocked",
                "detail": "No proof-grade video, rrweb, or image playback item is present in media-manifest.json.",
                "refType": "path",
                "ref": "media-manifest.json",
            }
        ],
        "caption": caption,
        "narration": "The media scene carries structured playback references so Slidey can render the recorded journey clips.",
    }


def _driver_scene(driver_plan: dict[str, Any], driver_journal: dict[str, Any]) -> dict[str, Any] | None:
    scenarios = [item for item in _as_list(driver_plan.get("scenarios")) if isinstance(item, dict)]
    events = [item for item in _as_list(driver_journal.get("items")) if isinstance(item, dict)]
    if not scenarios and not events:
        return None
    items = [
        {
            "label": str(item.get("scenario", "scenario")),
            "status": "validated",
            "detail": _short(f"{item.get('harness', '')} / {item.get('visual_surface', '')}", limit=150),
            "refType": "artifact",
            "ref": "driver-plan.json",
        }
        for item in scenarios[:2]
    ]
    items.extend(
        {
            "label": str(item.get("event_id", item.get("id", "driver event"))),
            "status": "done",
            "detail": _short(item.get("summary", item.get("action", "")), limit=140),
            "refType": "log",
            "ref": "driver-journal.json",
        }
        for item in events[: max(0, 4 - len(items))]
    )
    total = len(scenarios) + len(events)
    caption = "Harness choices and journal events behind the playback evidence."
    if total > len(items):
        caption = f"Showing {len(items)} of {total} driver records; full details remain in driver-plan.json and driver-journal.json."
    return {
        "type": "evidence",
        "title": "Driver contract",
        "items": items[:4],
        "caption": caption,
        "narration": "The driver scene records the capture harness and journal trail behind the visible playback evidence.",
    }


def _playback_candidates(media_manifest: dict[str, Any]) -> list[dict[str, Any]]:
    items = []
    for item in _as_list(media_manifest.get("items")):
        if not isinstance(item, dict):
            continue
        path = str(item.get("path", ""))
        media_kind = str(item.get("media_kind", ""))
        evidence_kind = str(item.get("evidence_kind", ""))
        if item.get("playback") or media_kind in {"video", "image"} or path.endswith(".rrweb.json") or "video" in evidence_kind:
            items.append(item)
    return sorted(
        items,
        key=lambda item: (
            str(item.get("scenario", "")),
            str(item.get("evidence_kind", "")),
            str(item.get("path", "")),
        ),
    )


def _classify_playback_items(playback_items: list[dict[str, Any]], run_dir: Path) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    verified: list[dict[str, Any]] = []
    blocked: list[dict[str, Any]] = []
    invalid_claims: list[str] = []
    for item in playback_items:
        ok, reason = _playback_trust(item, run_dir)
        if ok:
            verified.append({**item, "proof_status": "verified"})
            continue
        blocked_item = {**item, "proof_status": "blocked", "proof_reason": reason}
        blocked.append(blocked_item)
        if _claims_proof_playback(item):
            invalid_claims.append(
                f"{item.get('scenario', 'media')}/{item.get('evidence_kind', 'playback')}: {reason}"
            )
    if invalid_claims:
        raise PlaybackEvidenceError(
            "media-manifest.json claims playback evidence that is not proof-grade: "
            + "; ".join(invalid_claims)
        )
    return verified, blocked


def _claims_proof_playback(item: dict[str, Any]) -> bool:
    if str(item.get("status", "")) not in {"captured", "validated"}:
        return False
    if not str(item.get("path", "")):
        return False
    return not _explicitly_non_proof(item)


def _explicitly_non_proof(item: dict[str, Any]) -> bool:
    source = str(item.get("source", "")).strip().lower()
    provenance = _as_dict(item.get("capture_provenance") or item.get("provenance"))
    kind = str(provenance.get("kind", "")).strip().lower()
    combined = " ".join(str(item.get(key, "")) for key in ("path", "notes", "summary")).lower()
    return (
        item.get("proof") is False
        or source in NON_PROOF_SOURCES
        or kind in NON_PROOF_SOURCES
        or any(word in combined for word in NON_PROOF_WORDS)
    )


def _playback_trust(item: dict[str, Any], run_dir: Path) -> tuple[bool, str]:
    if str(item.get("status", "")) not in {"captured", "validated"}:
        return False, f"status is {item.get('status', 'missing')}"
    path = str(item.get("path", "")).strip()
    if not path:
        return False, "missing playback path"
    if _explicitly_non_proof(item):
        return False, "declared non-proof/demo playback"
    source = str(item.get("source", "")).strip().lower()
    if source not in PROOF_SOURCES:
        return False, f"source {source or 'missing'} is not proof-grade"
    provenance = _as_dict(item.get("capture_provenance") or item.get("provenance"))
    if not provenance:
        return False, "missing capture_provenance"
    if source in LOCAL_PROOF_SOURCES:
        resolved = _resolve_artifact_path(path, run_dir)
        if resolved is None:
            return False, "local playback path does not resolve"
        if path.endswith(".rrweb.json"):
            return _rrweb_is_proof_shaped(resolved)
    return True, "verified"


def _resolve_artifact_path(value: str, run_dir: Path) -> Path | None:
    path = Path(value)
    if path.is_absolute():
        return path if path.exists() else None
    candidates = [
        run_dir / path,
        REPO_ROOT / path,
        REPO_ROOT / "docs" / "decks" / path,
        Path.cwd() / path,
        Path.cwd() / "docs" / "decks" / path,
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def _rrweb_is_proof_shaped(path: Path) -> tuple[bool, str]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return False, f"rrweb clip cannot be read: {exc}"
    events = data if isinstance(data, list) else _as_list(_as_dict(data).get("events"))
    if len(events) < MIN_RRWEB_EVENTS:
        return False, f"rrweb clip has only {len(events)} events"
    first_href = ""
    for event in events:
        if isinstance(event, dict) and event.get("type") == 4:
            first_href = str(_as_dict(event.get("data")).get("href", ""))
            break
    if not first_href or first_href == "about:blank":
        return False, "rrweb clip starts at about:blank"
    if not any(isinstance(event, dict) and event.get("type") == 2 for event in events):
        return False, "rrweb clip is missing a full snapshot event"
    return True, "verified rrweb capture"


def _playback_scenes(playback_items: list[dict[str, Any]], *, max_playback_scenes: int) -> list[dict[str, Any]]:
    scenes = []
    for item in playback_items[:max_playback_scenes]:
        scene = _playback_scene(item)
        if scene is not None:
            scenes.append(scene)
    return scenes


def _playback_scene(item: dict[str, Any]) -> dict[str, Any] | None:
    path = str(item.get("path", ""))
    if not path:
        return None
    title = " / ".join(part for part in [str(item.get("scenario", "")), str(item.get("evidence_kind", ""))] if part)
    if not title:
        title = Path(path).name
    media_kind = str(item.get("media_kind", ""))
    caption = str(item.get("notes") or path)
    if media_kind == "image":
        return {
            "type": "image",
            "title": title,
            "src": path,
            "fit": "contain",
            "caption": caption,
            "narration": f"Screenshot evidence for {title}.",
        }
    scene = {
        "type": "video",
        "mode": "embedded",
        "eyebrow": "Playback evidence",
        "title": title,
        "chapters": "auto",
        "caption": caption,
        "narration": f"Recorded playback evidence for {title}.",
    }
    if path.endswith(".rrweb.json"):
        scene["rrweb"] = path
    else:
        scene["src"] = path
    return scene


def _slidey_status(status: str) -> str:
    if status in {"validated", "implemented", "done", "issue", "blocked", "next", "progress", "pending", "skipped"}:
        return status
    if status in {"captured", "fixed", "pass"}:
        return "validated"
    if status in {"warn", "warning", "fail", "failed", "error"}:
        return "issue"
    if status in {"missing", "planned", "not_started"}:
        return "pending"
    return "done"


def _objective_status(status: str) -> str:
    normalized = _slidey_status(status)
    if normalized in {"validated", "implemented"}:
        return "done"
    return normalized


def _next_scene(run_dir: str, playback_scenes: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "type": "evidence",
        "title": "Regenerate from source artifacts",
        "items": [
            {
                "label": "Run bundle",
                "status": "done",
                "detail": f"Playback scenes: {len(playback_scenes)}",
                "refType": "path",
                "ref": run_dir,
            },
            {
                "label": "Regenerate",
                "status": "done",
                "detail": "Rebuild the deck from the run bundle.",
                "refType": "command",
                "ref": "python3 tools/persona_qa/kit.py deck --run-dir <run-dir> --out <deck.slidey.json>",
            },
            {
                "label": "Publish",
                "status": "next",
                "detail": "Commit the deck JSON and bundle the product-site viewer under docs/decks/bundled/.",
                "refType": "command",
                "ref": "slidey bundle <deck.slidey.json> docs/decks/bundled/<deck>.html",
            },
        ],
        "caption": "Generated decks are derived from run artifacts; change the source bundle or generator, then regenerate.",
        "narration": "The deck is a derived artifact. The durable source is the run bundle plus the recorded media manifest.",
    }
