#!/usr/bin/env python3
"""Build standardized Slidey report decks from structured workflow artifacts.

This tool is deliberately offline-only. It reads JSON artifacts produced by
workflow gates, harnesses, or deterministic scripts and writes a Slidey JSON
spec. It never asks an LLM to draft deck prose. LLM-authored summaries may be
included only when they already exist in the input artifact.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


THEME = "rose-pine-moon"
RESOLUTION = {"width": 1920, "height": 1080}
STATUSES = {"done", "next", "blocked", "pending", "failed", "validated", "implemented"}
FANOUT_STATUSES = {"succeeded", "failed", "retried", "skipped", "pending", "running", "blocked"}


def load_json(path: str | Path) -> Any:
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: str | Path, value: Any) -> None:
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "w", encoding="utf-8") as fh:
        json.dump(value, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def write_markdown(path: str | Path, title: str, summary: str, refs: list[dict[str, str]]) -> None:
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# {title}", "", summary, "", "## Review links"]
    for ref in refs:
        label = ref.get("label") or ref.get("path") or ref.get("ref") or "artifact"
        target = ref.get("path") or ref.get("ref") or ""
        status = ref.get("status", "")
        lines.append(f"- {label}: `{target}`" + (f" ({status})" if status else ""))
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def status(value: str) -> str:
    value = (value or "").lower()
    if value in STATUSES:
        return value
    if value in {"solved", "pass", "passed", "ok", "green"}:
        return "done"
    if value in {"partial", "queued", "running"}:
        return "pending"
    if value in {"fail", "red", "error"}:
        return "failed"
    return "pending"


def money(value: Any) -> str:
    if value in (None, "", 0, 0.0):
        return "-"
    try:
        return f"${float(value):.2f}"
    except (TypeError, ValueError):
        return str(value)


def num(value: Any) -> str:
    if value in (None, ""):
        return "-"
    if isinstance(value, float):
        return f"{value:.3g}"
    return str(value)


def require_list(data: dict[str, Any], key: str, kind: str) -> list[Any]:
    value = data.get(key) or []
    if not isinstance(value, list):
        raise SystemExit(f"{kind}: {key} must be a list")
    return value


def require_media_path(media: dict[str, Any], kind: str) -> None:
    if not (media.get("rrweb") or media.get("src") or media.get("path")):
        raise SystemExit(f"{kind}: media item {media.get('title') or media.get('label') or '?'} needs rrweb, src, or path")


def title_deck(title: str, subtitle: str, scenes: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "_comment": (
            "Generated by tools/report-deck/deterministic_deck.py from structured "
            "artifacts. Do not hand-edit generated output; update the source data."
        ),
        "meta": {"title": title, "resolution": RESOLUTION, "theme": THEME},
        "scenes": [
            {
                "type": "title",
                "eyebrow": "Kitsoki report",
                "title": title,
                "subtitle": subtitle,
                "hold": 1800,
            },
            *scenes,
        ],
    }


def media_scene(media: dict[str, Any], eyebrow: str) -> dict[str, Any]:
    require_media_path(media, "media")
    scene = {
        "type": "video",
        "mode": "embedded",
        "eyebrow": media.get("eyebrow", eyebrow),
        "title": media.get("title") or media.get("label") or "Playback",
        "caption": media.get("caption", ""),
        "hold": media.get("hold", 2400),
    }
    if media.get("rrweb"):
        scene["rrweb"] = media["rrweb"]
        scene["chapters"] = media.get("chapters", "auto")
    else:
        scene["src"] = media.get("src") or media.get("path", "")
        if media.get("chapters"):
            scene["chapters"] = media["chapters"]
    return scene


def evidence_scene(title: str, items: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "type": "evidence",
        "title": title,
        "items": [
            {
                "label": str(i.get("label", "artifact")),
                "status": status(str(i.get("status", "pending"))),
                "detail": str(i.get("detail", "")),
                "refType": str(i.get("refType", "path")),
                "ref": str(i.get("ref") or i.get("path") or ""),
            }
            for i in items
        ],
        "hold": 2200,
    }


def objectives_scene(title: str, items: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "type": "objectives",
        "title": title,
        "items": [
            {
                "label": str(i.get("label", "objective")),
                "status": status(str(i.get("status", "pending"))),
                "detail": str(i.get("detail", "")),
            }
            for i in items
        ],
        "hold": 2400,
    }


def bakeoff_summary(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    cells = data.get("cells", [])
    bugs = data.get("bugs", [])
    rollup = data.get("rollup", {})
    by_treatment = rollup.get("by_treatment", {})
    by_candidate = rollup.get("by_candidate", {})
    total = len(cells)
    solved = sum(1 for c in cells if c.get("outcome", {}).get("quality") == "solved")
    title = "Bugfix Bake-off"
    subtitle = f"{total} scored cells, {solved} solved, generated from summary JSON"

    objectives = [
        {"label": "Scored cells", "status": "done" if total else "pending", "detail": f"{total} cell artifact(s) loaded."},
        {"label": "Hidden-oracle grading", "status": "done", "detail": "Outcomes come from scored cell JSON, not self-report."},
        {"label": "Remaining grid", "status": "next" if bugs and total else "pending", "detail": f"{len(bugs)} bug fixture(s) in manifest."},
    ]

    treatment_rows = []
    for name, bucket in sorted(by_treatment.items()):
        treatment_rows.append({"cells": [
            name,
            num(bucket.get("n")),
            num(bucket.get("solved")),
            num(bucket.get("solve_rate")),
            money(bucket.get("avg_cost_usd")),
            num(bucket.get("avg_guidance_turns")),
        ]})

    candidate_rows = []
    for name, bucket in sorted(by_candidate.items()):
        candidate_rows.append({"cells": [
            name,
            num(bucket.get("n")),
            num(bucket.get("solved")),
            num(bucket.get("solve_rate")),
            money(bucket.get("avg_cost_usd")),
            num(bucket.get("avg_total_tokens")),
        ]})

    cell_rows = []
    for c in sorted(cells, key=lambda x: (x.get("bug", ""), x.get("candidate", ""), x.get("treatment", "")))[:12]:
        out = c.get("outcome", {})
        metrics = c.get("metrics", {})
        cell_rows.append({"cells": [
            c.get("bug", ""),
            c.get("candidate", ""),
            c.get("treatment", ""),
            out.get("quality", ""),
            money(metrics.get("cost_usd")),
            num(metrics.get("guidance_turns")),
        ]})

    scenes: list[dict[str, Any]] = [
        objectives_scene("Objective status", objectives),
        {
            "type": "table",
            "variant": "data",
            "title": "Treatment rollup",
            "columns": ["Treatment", "Cells", "Solved", "Solve rate", "Avg cost", "Avg turns"],
            "rows": treatment_rows or [{"cells": ["-", "0", "0", "-", "-", "-"]}],
            "hold": 2600,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Candidate rollup",
            "columns": ["Candidate", "Cells", "Solved", "Solve rate", "Avg cost", "Avg tokens"],
            "rows": candidate_rows or [{"cells": ["-", "0", "0", "-", "-", "-"]}],
            "hold": 2600,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Scored cells",
            "columns": ["Bug", "Candidate", "Treatment", "Outcome", "Cost", "Turns"],
            "rows": cell_rows or [{"cells": ["-", "-", "-", "pending", "-", "-"]}],
            "caption": "Limited to the first 12 cells for readability; the JSON summary remains authoritative.",
            "hold": 3000,
        },
        evidence_scene("Review artifacts", [
            {"label": "Summary JSON", "status": "done", "detail": "Authoritative rollup and cell source.", "ref": str(data.get("_source", ""))},
            {"label": "Manifest", "status": "done", "detail": "Fixture, candidate, and treatment axes.", "ref": str(data.get("manifest", ""))},
        ]),
    ]
    return title_deck(title, subtitle, scenes), [
        {"label": "Summary JSON", "path": str(data.get("_source", "")), "status": "done"},
        {"label": "Manifest", "path": str(data.get("manifest", "")), "status": "done"},
    ]


def external_summary(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    project = data.get("project", "external project")
    cells = data.get("cells", [])
    by_candidate = data.get("rollup", {}).get("by_candidate", {})
    title = f"{project} Bake-off"
    solved = sum(1 for c in cells if c.get("outcome", {}).get("quality") == "solved")
    subtitle = f"{len(cells)} scored cells, {solved} solved, external oracle grading"
    rows = []
    for name, bucket in sorted(by_candidate.items()):
        rows.append({"cells": [
            name,
            num(bucket.get("n")),
            num(bucket.get("solved")),
            num(bucket.get("partial")),
            num(bucket.get("failed")),
            num(bucket.get("solve_rate")),
        ]})
    cell_rows = []
    for c in sorted(cells, key=lambda x: (x.get("bug", ""), x.get("candidate", ""), x.get("treatment", "")))[:12]:
        cell_rows.append({"cells": [
            c.get("bug", ""),
            c.get("candidate", ""),
            c.get("treatment", ""),
            c.get("outcome", {}).get("quality", ""),
            c.get("outcome", {}).get("oracle_status", ""),
        ]})
    scenes = [
        objectives_scene("Objective status", [
            {"label": "Fixtures armed", "status": "done", "detail": "Fixtures are expected to be RED at baseline and GREEN at maintainer fix."},
            {"label": "Candidate fixes", "status": "done" if cells else "pending", "detail": f"{len(cells)} scored candidate cell(s)."},
            {"label": "Next review", "status": "next", "detail": "Inspect partial/failed rows against the hidden oracle output."},
        ]),
        {"type": "table", "variant": "data", "title": "Candidate outcomes", "columns": ["Candidate", "Cells", "Solved", "Partial", "Failed", "Solve rate"], "rows": rows or [{"cells": ["-", "0", "0", "0", "0", "-"]}], "hold": 2600},
        {"type": "table", "variant": "data", "title": "Scored cells", "columns": ["Bug", "Candidate", "Treatment", "Quality", "Oracle"], "rows": cell_rows or [{"cells": ["-", "-", "-", "pending", "-"]}], "hold": 2800},
        evidence_scene("Review artifacts", [{"label": "Summary JSON", "status": "done", "detail": "External benchmark rollup.", "ref": str(data.get("_source", ""))}]),
    ]
    return title_deck(title, subtitle, scenes), [{"label": "Summary JSON", "path": str(data.get("_source", "")), "status": "done"}]


def onboarding(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    project = data.get("project_title") or data.get("init_project_title") or data.get("project_id") or "Project onboarding"
    target = data.get("target_path") or data.get("init_target_path") or ""
    apply = data.get("apply_result") or data.get("init_apply_result") or {}
    writes = apply.get("writes") or []
    title = f"{project} Onboarding"
    scenes = [
        objectives_scene("Objective status", [
            {"label": "Project discovery", "status": "done", "detail": data.get("stack") or data.get("init_stack") or "Discovery artifact loaded."},
            {"label": "Local setup files", "status": "implemented" if apply else "pending", "detail": f"{len(writes)} write(s) recorded."},
            {"label": "Operator review", "status": "next", "detail": "Review generated config, profile, commands, and tracker assumptions."},
        ]),
        evidence_scene("Applied artifacts", [
            {"label": "Target", "status": "done", "detail": "Onboarded checkout.", "ref": target},
            {"label": "Config", "status": "implemented", "detail": ".kitsoki.yaml", "ref": apply.get("config_path", "")},
            {"label": "Profile", "status": "implemented", "detail": "project-profile/v1", "ref": apply.get("profile_path", "")},
            {"label": "Instance", "status": "implemented", "detail": "Project story instance.", "ref": apply.get("instance_path", "")},
        ]),
        {"type": "table", "variant": "data", "title": "Commands", "columns": ["Purpose", "Command"], "rows": [
            {"cells": ["Dev", data.get("dev_command") or data.get("init_dev_command") or "-"]},
            {"cells": ["Test", data.get("test_command") or data.get("init_test_command") or "-"]},
            {"cells": ["Build", data.get("build_command") or data.get("init_build_command") or "-"]},
        ], "hold": 2200},
    ]
    refs = [{"label": "Target", "path": target, "status": "done"}]
    refs.extend({"label": Path(w).name, "path": str(w), "status": "implemented"} for w in writes)
    return title_deck(title, f"Deterministic onboarding review for {target}", scenes), refs


def workflow(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    title = data.get("title") or data.get("name") or "Workflow Report"
    objectives = data.get("objectives") or []
    artifacts = data.get("artifacts") or data.get("evidence") or []
    next_steps = data.get("next_steps") or []
    rows = []
    for item in data.get("items", [])[:12]:
        rows.append({"cells": [
            item.get("id") or item.get("label") or "",
            item.get("status") or item.get("quality") or "",
            item.get("owner") or item.get("candidate") or "",
            item.get("artifact") or item.get("path") or "",
        ]})
    scenes = [
        objectives_scene("Objective status", objectives or [{"label": "Workflow", "status": "pending", "detail": "No objective list was provided."}]),
        evidence_scene("Review artifacts", artifacts),
    ]
    if rows:
        scenes.append({"type": "table", "variant": "data", "title": "Work items", "columns": ["Item", "Status", "Owner", "Artifact"], "rows": rows, "hold": 2600})
    for media in data.get("media", [])[:6]:
        scenes.append(media_scene(media, "Workflow media"))
    if next_steps:
        scenes.append(objectives_scene("Next steps", [{"label": s.get("label", "next"), "status": "next", "detail": s.get("detail", "")} for s in next_steps]))
    return title_deck(title, data.get("summary", "Deterministic workflow deck"), scenes), [
        {"label": a.get("label", "artifact"), "path": a.get("ref") or a.get("path", ""), "status": a.get("status", "")}
        for a in artifacts
    ]


def feature_demo(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    title = data.get("title") or "Feature Development Demo"
    phases = require_list(data, "phases", "feature-demo")
    media = require_list(data, "media", "feature-demo")
    personas = data.get("personas") or []
    scenes: list[dict[str, Any]] = [
        objectives_scene("Objective status", data.get("objectives") or [
            {"label": "Feature demo", "status": "done" if media else "pending", "detail": f"{len(media)} replay artifact(s) linked."},
            {"label": "Review path", "status": "next", "detail": "Review the embedded replay scenes and linked artifacts."},
        ]),
    ]
    meta_extra: dict[str, Any] = {}
    if personas:
        meta_extra["personas"] = personas
        scenes.append({
            "type": "personas",
            "variant": "cast",
            "title": "Cast",
            "personas": [p.get("id", "") for p in personas if p.get("id")],
            "caption": data.get("cast_caption", ""),
        })
    if phases:
        scenes.append({
            "type": "personas",
            "variant": "use-cases",
            "title": "Feature path",
            "cases": [
                {
                    "who": p.get("who", p.get("persona", "")),
                    "action": p.get("action") or p.get("label", ""),
                    "detail": p.get("detail", p.get("status", "")),
                }
                for p in phases
            ],
        })
    for item in media[:8]:
        scenes.append(media_scene(item, "Feature replay"))
    deck = title_deck(title, data.get("summary", "Feature progress replay deck"), scenes)
    deck["meta"].update(meta_extra)
    refs = [{"label": m.get("title", "media"), "path": m.get("rrweb") or m.get("src") or m.get("path", ""), "status": "done"} for m in media]
    refs.extend({"label": a.get("label", "artifact"), "path": a.get("ref") or a.get("path", ""), "status": a.get("status", "")} for a in data.get("artifacts", []))
    return deck, refs


def bug_report(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    title = data.get("title") or data.get("bug") or "Bug Report"
    evidence = require_list(data, "evidence", "bug-report")
    media = require_list(data, "media", "bug-report")
    if not (evidence or media):
        raise SystemExit("bug-report: evidence or media is required")
    repro = data.get("reproducer", {})
    scenes: list[dict[str, Any]] = [
        objectives_scene("Bug status", [
            {"label": "Triage", "status": status(data.get("triage_status", "done")), "detail": data.get("summary", "")},
            {"label": "Reproducer", "status": "done" if repro else "pending", "detail": repro.get("command", "No reproducer command provided.") if isinstance(repro, dict) else str(repro)},
            {"label": "Next action", "status": "next", "detail": data.get("next_action", "Review linked evidence and assign owner.")},
        ]),
        evidence_scene("Evidence", evidence),
    ]
    if isinstance(repro, dict) and repro:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Reproducer",
            "columns": ["Field", "Value"],
            "rows": [
                {"cells": ["Command", repro.get("command", "-")]},
                {"cells": ["Expected", repro.get("expected", "-")]},
                {"cells": ["Actual", repro.get("actual", "-")]},
            ],
            "hold": 2400,
        })
    for item in media[:4]:
        scenes.append(media_scene(item, "Bug playback"))
    refs = [{"label": e.get("label", "evidence"), "path": e.get("ref") or e.get("path", ""), "status": e.get("status", "")} for e in evidence]
    refs.extend({"label": m.get("title", "playback"), "path": m.get("rrweb") or m.get("src") or m.get("path", ""), "status": "done"} for m in media)
    return title_deck(title, data.get("summary", "Deterministic bug report deck"), scenes), refs


def fanout(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    title = data.get("title") or "Fan-out Job Report"
    items = require_list(data, "items", "fanout")
    if not items:
        raise SystemExit("fanout: items are required")
    counts = {key: 0 for key in FANOUT_STATUSES}
    rows = []
    for item in items:
        item_status = str(item.get("status", "pending")).lower()
        if item_status not in FANOUT_STATUSES:
            raise SystemExit(f"fanout: unsupported status {item_status!r}")
        counts[item_status] += 1
        rows.append({"cells": [
            item.get("id") or item.get("label") or "",
            item_status,
            num(item.get("attempts", "")),
            item.get("owner") or item.get("worker") or "",
            item.get("artifact") or item.get("path") or item.get("trace") or "",
        ]})
    total = len(items)
    scenes = [
        objectives_scene("Job status", [
            {"label": "Succeeded", "status": "done" if counts["succeeded"] else "pending", "detail": f"{counts['succeeded']} of {total} item(s)."},
            {"label": "Failed", "status": "failed" if counts["failed"] else "done", "detail": f"{counts['failed']} item(s)."},
            {"label": "Retried", "status": "pending" if counts["retried"] else "done", "detail": f"{counts['retried']} item(s)."},
            {"label": "Still pending", "status": "pending" if counts["pending"] or counts["running"] else "done", "detail": f"{counts['pending'] + counts['running']} item(s)."},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Fan-out items",
            "columns": ["Item", "Status", "Attempts", "Owner", "Artifact"],
            "rows": rows[:18],
            "caption": "Rows are sourced from the job artifact; the full JSON remains authoritative.",
            "hold": 3200,
        },
    ]
    if data.get("next_steps"):
        scenes.append(objectives_scene("Next steps", [{"label": s.get("label", "next"), "status": "next", "detail": s.get("detail", "")} for s in data["next_steps"]]))
    refs = [{"label": i.get("id") or i.get("label", "item"), "path": i.get("artifact") or i.get("path") or i.get("trace", ""), "status": i.get("status", "")} for i in items]
    return title_deck(title, f"{counts['succeeded']} succeeded, {counts['failed']} failed, {counts['retried']} retried", scenes), refs


def product_journey(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    title = data.get("title") or data.get("program") or "Product Journey Eval"
    targets = require_list(data, "targets", "product-journey")
    perspectives = require_list(data, "perspectives", "product-journey")
    checks = data.get("checks") or {}
    validated = sum(1 for t in targets if status(checks.get(t.get("id", ""), {}).get("status") or t.get("status")) in {"done", "validated"})
    rows = []
    for target in targets:
        target_id = target.get("id", "")
        check = checks.get(target_id, {}) if isinstance(checks, dict) else {}
        rows.append({"cells": [
            target_id,
            target.get("stack", ""),
            check.get("status") or target.get("status", ""),
            target.get("run_mode", ""),
            target.get("manifest") or target.get("validation_command") or target.get("run_command") or "",
        ]})
    perspective_rows = [
        {"cells": [p.get("id", ""), p.get("owner", ""), p.get("status", ""), p.get("description", "")]}
        for p in perspectives
    ]
    scenes = [
        objectives_scene("Objective status", [
            {"label": "Harness", "status": "done", "detail": "tools/product-journey/run.py emits deterministic structured reports."},
            {"label": "Project lanes", "status": "done" if validated == len(targets) else "pending", "detail": f"{validated} of {len(targets)} target(s) validated or cached."},
            {"label": "Hand-refined reference", "status": "done", "detail": data.get("reference_deck", "No reference deck recorded.")},
            {"label": "Product-site journey", "status": "next", "detail": data.get("next_site_journey", "Run the local product site journey when ready.")},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Target lanes",
            "columns": ["Target", "Stack", "Status", "Mode", "Evidence"],
            "rows": rows,
            "hold": 3000,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Perspectives",
            "columns": ["Perspective", "Owner", "Status", "Description"],
            "rows": perspective_rows or [{"cells": ["-", "-", "-", "-"]}],
            "hold": 2600,
        },
        evidence_scene("Review artifacts", [
            {"label": "Reference deck", "status": "done", "detail": "Hand-refined narrative reference; generated reports do not overwrite it.", "ref": data.get("reference_deck", "")},
            {"label": "Catalog", "status": "done", "detail": "Project and perspective registry.", "ref": data.get("catalog", "")},
            {"label": "Run log", "status": "implemented", "detail": "Chronological operator log when status/check modes are run.", "ref": data.get("run_log", "")},
            {"label": "Generated summary", "status": "done", "detail": "Structured input used to build this deck.", "ref": str(data.get("_source", ""))},
        ]),
    ]
    if data.get("next_steps"):
        scenes.append(objectives_scene("Next steps", data["next_steps"]))
    refs = [
        {"label": "Reference deck", "path": data.get("reference_deck", ""), "status": "done"},
        {"label": "Catalog", "path": data.get("catalog", ""), "status": "done"},
        {"label": "Run log", "path": data.get("run_log", ""), "status": "implemented"},
    ]
    return title_deck(title, data.get("summary", "Deterministic product-journey report"), scenes), refs


BUILDERS = {
    "bakeoff-summary": bakeoff_summary,
    "bug-report": bug_report,
    "external-summary": external_summary,
    "fanout": fanout,
    "feature-demo": feature_demo,
    "onboarding": onboarding,
    "product-journey": product_journey,
    "workflow": workflow,
}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--kind", choices=sorted(BUILDERS), required=True)
    ap.add_argument("--input", help="structured JSON input")
    ap.add_argument("--input-json", help="structured JSON input as a string; overrides --input")
    ap.add_argument("--out", required=True, help="Slidey JSON spec to write")
    ap.add_argument("--markdown", help="optional Markdown review index")
    ap.add_argument("--summary-out", help="optional machine-readable build summary")
    args = ap.parse_args(argv)

    if args.input_json:
        data = json.loads(args.input_json)
    elif args.input:
        data = load_json(args.input)
    else:
        raise SystemExit("deterministic_deck.py: --input or --input-json is required")
    if isinstance(data, dict):
        data.setdefault("_source", args.input)
    deck, refs = BUILDERS[args.kind](data)
    write_json(args.out, deck)
    summary = {
        "kind": args.kind,
        "spec_path": args.out,
        "summary": deck["scenes"][0].get("subtitle", ""),
        "title": deck["meta"]["title"],
        "artifacts": refs,
    }
    if args.markdown:
        write_markdown(args.markdown, summary["title"], summary["summary"], refs)
        summary["markdown_path"] = args.markdown
    if args.summary_out:
        write_json(args.summary_out, summary)
    print(json.dumps(summary, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
