#!/usr/bin/env python3
"""Build standardized Slidey report decks from structured workflow artifacts.

This tool is deliberately offline-only. It reads JSON artifacts produced by
workflow gates, harnesses, or deterministic scripts and writes a Slidey JSON
spec. It never asks an LLM to draft deck prose. LLM-authored summaries may be
included only when they already exist in the input artifact.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any


THEME = "rose-pine-moon"
RESOLUTION = {"width": 1920, "height": 1080}
STATUSES = {"done", "next", "blocked", "pending", "failed", "validated", "implemented"}
FANOUT_STATUSES = {"succeeded", "failed", "retried", "skipped", "pending", "running", "blocked"}


def load_json(path: str | Path) -> Any:
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def write_json(path: str | Path, value: Any) -> None:
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    with open(dest, "w", encoding="utf-8") as fh:
        json.dump(value, fh, indent=2, ensure_ascii=False)
        fh.write("\n")


def write_markdown(path: str | Path, title: str, summary: str, refs: list[dict[str, str]]) -> None:
    dest = Path(path)
    dest.parent.mkdir(parents=True, exist_ok=True)
    lines = [f"# {title}", "", summary, "", "## Review links"]
    for ref in refs:
        label = ref.get("label") or ref.get("path") or ref.get("ref") or "artifact"
        target = ref.get("path") or ref.get("ref") or ""
        status = ref.get("status", "")
        lines.append(f"- {label}: `{target}`" + (f" ({status})" if status else ""))
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")


def slug(value: str) -> str:
    out = []
    for ch in (value or "").lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in {"-", "_", ".", ":", " "}:
            out.append("-")
    text = "".join(out).strip("-")
    while "--" in text:
        text = text.replace("--", "-")
    return text or "run"


def slug_path(value: str) -> Path:
    parts = [slug(part) for part in (value or "").replace("\\", "/").split("/") if part.strip()]
    if not parts:
        return Path("job")
    return Path(*parts)


def artifact_paths(args: argparse.Namespace) -> tuple[str, str]:
    if args.out:
        out = args.out
        markdown = args.markdown or ""
        return out, markdown
    if not args.job:
        raise SystemExit("deterministic_deck.py: --out or --job is required")
    run_id = slug(args.run_id or "latest")
    base = Path(args.artifact_root) / slug_path(args.job) / run_id
    out = str(base / "deck.slidey.json")
    markdown = args.markdown if args.markdown is not None else str(base / "report.md")
    return out, markdown


def status(value: str) -> str:
    value = (value or "").lower()
    if value in STATUSES:
        return value
    if value in {"solved", "pass", "passed", "ok", "green"}:
        return "done"
    if value in {"partial", "queued", "running"}:
        return "pending"
    if value in {"fail", "red", "error"}:
        return "failed"
    return "pending"


def money(value: Any) -> str:
    if value in (None, "", 0, 0.0):
        return "-"
    try:
        return f"${float(value):.2f}"
    except (TypeError, ValueError):
        return str(value)


def num(value: Any) -> str:
    if value in (None, ""):
        return "-"
    if isinstance(value, float):
        return f"{value:.3g}"
    return str(value)


def require_list(data: dict[str, Any], key: str, kind: str) -> list[Any]:
    value = data.get(key) or []
    if not isinstance(value, list):
        raise SystemExit(f"{kind}: {key} must be a list")
    return value


def require_media_path(media: dict[str, Any], kind: str) -> None:
    if not (media.get("rrweb") or media.get("src") or media.get("path")):
        raise SystemExit(f"{kind}: media item {media.get('title') or media.get('label') or '?'} needs rrweb, src, or path")


def title_deck(title: str, subtitle: str, scenes: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "_comment": (
            "Generated by tools/report-deck/deterministic_deck.py from structured "
            "artifacts. Do not hand-edit generated output; update the source data."
        ),
        "meta": {"title": title, "resolution": RESOLUTION, "theme": THEME},
        "scenes": [
            {
                "type": "title",
                "eyebrow": "Kitsoki report",
                "title": title,
                "subtitle": subtitle,
                "hold": 1800,
            },
            *scenes,
        ],
    }


def media_scene(media: dict[str, Any], eyebrow: str) -> dict[str, Any]:
    require_media_path(media, "media")
    scene = {
        "type": "video",
        "mode": "embedded",
        "eyebrow": media.get("eyebrow", eyebrow),
        "title": media.get("title") or media.get("label") or "Playback",
        "caption": media.get("caption", ""),
        "hold": media.get("hold", 2400),
    }
    if media.get("rrweb"):
        scene["rrweb"] = media["rrweb"]
        scene["chapters"] = media.get("chapters", "auto")
    else:
        scene["src"] = media.get("src") or media.get("path", "")
        if media.get("chapters"):
            scene["chapters"] = media["chapters"]
    return scene


def evidence_scene(title: str, items: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "type": "evidence",
        "title": title,
        "items": [
            {
                "label": str(i.get("label", "artifact")),
                "status": status(str(i.get("status", "pending"))),
                "detail": str(i.get("detail", "")),
                "refType": str(i.get("refType", "path")),
                "ref": str(i.get("ref") or i.get("path") or ""),
            }
            for i in items
        ],
        "hold": 2200,
    }


def objectives_scene(title: str, items: list[dict[str, Any]]) -> dict[str, Any]:
    return {
        "type": "objectives",
        "title": title,
        "items": [
            {
                "label": str(i.get("label", "objective")),
                "status": status(str(i.get("status", "pending"))),
                "detail": str(i.get("detail", "")),
            }
            for i in items
        ],
        "hold": 2400,
    }


def bakeoff_summary(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    cells = data.get("cells", [])
    bugs = data.get("bugs", [])
    rollup = data.get("rollup", {})
    by_treatment = rollup.get("by_treatment", {})
    by_candidate = rollup.get("by_candidate", {})
    total = len(cells)
    solved = sum(1 for c in cells if c.get("outcome", {}).get("quality") == "solved")
    title = "Bugfix Bake-off"
    subtitle = f"{total} scored cells, {solved} solved, generated from summary JSON"

    objectives = [
        {"label": "Scored cells", "status": "done" if total else "pending", "detail": f"{total} cell artifact(s) loaded."},
        {"label": "Hidden-oracle grading", "status": "done", "detail": "Outcomes come from scored cell JSON, not self-report."},
        {"label": "Remaining grid", "status": "next" if bugs and total else "pending", "detail": f"{len(bugs)} bug fixture(s) in manifest."},
    ]

    treatment_rows = []
    for name, bucket in sorted(by_treatment.items()):
        treatment_rows.append({"cells": [
            name,
            num(bucket.get("n")),
            num(bucket.get("solved")),
            num(bucket.get("solve_rate")),
            money(bucket.get("avg_cost_usd")),
            num(bucket.get("avg_guidance_turns")),
        ]})

    candidate_rows = []
    for name, bucket in sorted(by_candidate.items()):
        candidate_rows.append({"cells": [
            name,
            num(bucket.get("n")),
            num(bucket.get("solved")),
            num(bucket.get("solve_rate")),
            money(bucket.get("avg_cost_usd")),
            num(bucket.get("avg_total_tokens")),
        ]})

    cell_rows = []
    for c in sorted(cells, key=lambda x: (x.get("bug", ""), x.get("candidate", ""), x.get("treatment", "")))[:12]:
        out = c.get("outcome", {})
        metrics = c.get("metrics", {})
        cell_rows.append({"cells": [
            c.get("bug", ""),
            c.get("candidate", ""),
            c.get("treatment", ""),
            out.get("quality", ""),
            money(metrics.get("cost_usd")),
            num(metrics.get("guidance_turns")),
        ]})

    scenes: list[dict[str, Any]] = [
        objectives_scene("Objective status", objectives),
        {
            "type": "table",
            "variant": "data",
            "title": "Treatment rollup",
            "columns": ["Treatment", "Cells", "Solved", "Solve rate", "Avg cost", "Avg turns"],
            "rows": treatment_rows or [{"cells": ["-", "0", "0", "-", "-", "-"]}],
            "hold": 2600,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Candidate rollup",
            "columns": ["Candidate", "Cells", "Solved", "Solve rate", "Avg cost", "Avg tokens"],
            "rows": candidate_rows or [{"cells": ["-", "0", "0", "-", "-", "-"]}],
            "hold": 2600,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Scored cells",
            "columns": ["Bug", "Candidate", "Treatment", "Outcome", "Cost", "Turns"],
            "rows": cell_rows or [{"cells": ["-", "-", "-", "pending", "-", "-"]}],
            "caption": "Limited to the first 12 cells for readability; the JSON summary remains authoritative.",
            "hold": 3000,
        },
        evidence_scene("Review artifacts", [
            {"label": "Summary JSON", "status": "done", "detail": "Authoritative rollup and cell source.", "ref": str(data.get("_source", ""))},
            {"label": "Manifest", "status": "done", "detail": "Fixture, candidate, and treatment axes.", "ref": str(data.get("manifest", ""))},
        ]),
    ]
    return title_deck(title, subtitle, scenes), [
        {"label": "Summary JSON", "path": str(data.get("_source", "")), "status": "done"},
        {"label": "Manifest", "path": str(data.get("manifest", "")), "status": "done"},
    ]


def external_summary(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    project = data.get("project", "external project")
    cells = data.get("cells", [])
    by_candidate = data.get("rollup", {}).get("by_candidate", {})
    title = f"{project} Bake-off"
    solved = sum(1 for c in cells if c.get("outcome", {}).get("quality") == "solved")
    subtitle = f"{len(cells)} scored cells, {solved} solved, external oracle grading"
    rows = []
    for name, bucket in sorted(by_candidate.items()):
        rows.append({"cells": [
            name,
            num(bucket.get("n")),
            num(bucket.get("solved")),
            num(bucket.get("partial")),
            num(bucket.get("failed")),
            num(bucket.get("solve_rate")),
        ]})
    cell_rows = []
    for c in sorted(cells, key=lambda x: (x.get("bug", ""), x.get("candidate", ""), x.get("treatment", "")))[:12]:
        cell_rows.append({"cells": [
            c.get("bug", ""),
            c.get("candidate", ""),
            c.get("treatment", ""),
            c.get("outcome", {}).get("quality", ""),
            c.get("outcome", {}).get("oracle_status", ""),
        ]})
    scenes = [
        objectives_scene("Objective status", [
            {"label": "Fixtures armed", "status": "done", "detail": "Fixtures are expected to be RED at baseline and GREEN at maintainer fix."},
            {"label": "Candidate fixes", "status": "done" if cells else "pending", "detail": f"{len(cells)} scored candidate cell(s)."},
            {"label": "Next review", "status": "next", "detail": "Inspect partial/failed rows against the hidden oracle output."},
        ]),
        {"type": "table", "variant": "data", "title": "Candidate outcomes", "columns": ["Candidate", "Cells", "Solved", "Partial", "Failed", "Solve rate"], "rows": rows or [{"cells": ["-", "0", "0", "0", "0", "-"]}], "hold": 2600},
        {"type": "table", "variant": "data", "title": "Scored cells", "columns": ["Bug", "Candidate", "Treatment", "Quality", "Oracle"], "rows": cell_rows or [{"cells": ["-", "-", "-", "pending", "-"]}], "hold": 2800},
        evidence_scene("Review artifacts", [{"label": "Summary JSON", "status": "done", "detail": "External benchmark rollup.", "ref": str(data.get("_source", ""))}]),
    ]
    return title_deck(title, subtitle, scenes), [{"label": "Summary JSON", "path": str(data.get("_source", "")), "status": "done"}]


def onboarding(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    project = data.get("project_title") or data.get("init_project_title") or data.get("project_id") or "Project onboarding"
    target = data.get("target_path") or data.get("init_target_path") or ""
    apply = data.get("apply_result") or data.get("init_apply_result") or {}
    writes = apply.get("writes") or []
    title = f"{project} Onboarding"
    scenes = [
        objectives_scene("Objective status", [
            {"label": "Project discovery", "status": "done", "detail": data.get("stack") or data.get("init_stack") or "Discovery artifact loaded."},
            {"label": "Local setup files", "status": "implemented" if apply else "pending", "detail": f"{len(writes)} write(s) recorded."},
            {"label": "Operator review", "status": "next", "detail": "Review generated config, profile, commands, and tracker assumptions."},
        ]),
        evidence_scene("Applied artifacts", [
            {"label": "Target", "status": "done", "detail": "Onboarded checkout.", "ref": target},
            {"label": "Config", "status": "implemented", "detail": ".kitsoki.yaml", "ref": apply.get("config_path", "")},
            {"label": "Profile", "status": "implemented", "detail": "project-profile/v1", "ref": apply.get("profile_path", "")},
            {"label": "Instance", "status": "implemented", "detail": "Project story instance.", "ref": apply.get("instance_path", "")},
        ]),
        {"type": "table", "variant": "data", "title": "Commands", "columns": ["Purpose", "Command"], "rows": [
            {"cells": ["Dev", data.get("dev_command") or data.get("init_dev_command") or "-"]},
            {"cells": ["Test", data.get("test_command") or data.get("init_test_command") or "-"]},
            {"cells": ["Build", data.get("build_command") or data.get("init_build_command") or "-"]},
        ], "hold": 2200},
    ]
    refs = [{"label": "Target", "path": target, "status": "done"}]
    refs.extend({"label": Path(w).name, "path": str(w), "status": "implemented"} for w in writes)
    return title_deck(title, f"Deterministic onboarding review for {target}", scenes), refs


def model_harness(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    question = data.get("question") or "Model harness evaluation"
    recs = data.get("recommendations") or {}
    override = data.get("override") or {}
    evidence = data.get("evidence") or {}
    options = data.get("configured_options") or []
    limitations = data.get("limitations") or []
    commands = data.get("commands_run") or []

    def rec_row(name: str) -> dict[str, list[str]]:
        rec = recs.get(name) or {}
        return {"cells": [
            name,
            rec.get("profile", ""),
            rec.get("model", ""),
            rec.get("effort", ""),
            rec.get("evidence_status", ""),
            rec.get("rationale", ""),
        ]}

    option_rows = []
    for opt in options[:12]:
        option_rows.append({"cells": [
            opt.get("profile", ""),
            opt.get("backend", ""),
            opt.get("model", ""),
            opt.get("effort", ""),
            opt.get("source", ""),
        ]})
    evidence_rows = [{"cells": [key, num(value)]} for key, value in sorted(evidence.items())]
    command_rows = [{"cells": [str(i + 1), cmd]} for i, cmd in enumerate(commands[:10])]

    selected = recs.get("selected") or {}
    scenes = [
        objectives_scene("Recommendation status", [
            {"label": "Reporter artifact", "status": status(data.get("status", "")), "detail": data.get("status", "pending")},
            {"label": "Selected option", "status": status(selected.get("evidence_status", "")), "detail": f"{selected.get('profile', '')} / {selected.get('model', '')}"},
            {"label": "Override", "status": "implemented" if override.get("applied") else "pending", "detail": override.get("summary", "")},
            {"label": "Deck authoring", "status": "done", "detail": "This deck is deterministic from report_artifact.json."},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Recommendations",
            "columns": ["Type", "Profile", "Model", "Effort", "Evidence", "Rationale"],
            "rows": [rec_row(name) for name in ["fastest", "cheapest", "best", "selected"]],
            "hold": 3000,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Configured options",
            "columns": ["Profile", "Backend", "Model", "Effort", "Source"],
            "rows": option_rows or [{"cells": ["-", "-", "-", "-", "-"]}],
            "hold": 2600,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Evidence counts",
            "columns": ["Metric", "Value"],
            "rows": evidence_rows or [{"cells": ["evidence", "missing"]}],
            "hold": 2400,
        },
        evidence_scene("Review artifacts", [
            {"label": "Markdown report", "status": "done", "detail": "Narrative report.", "ref": data.get("markdown_path", "")},
            {"label": "Summary JSON", "status": "done", "detail": "Machine-readable rollup.", "ref": data.get("summary_path", "")},
            {"label": "Case study", "status": "done", "detail": "Durable case-study doc.", "ref": data.get("case_study_path", "")},
            {"label": "Report artifact", "status": "done", "detail": "Schema-validated input for this deterministic deck.", "ref": str(data.get("_source", ""))},
        ]),
    ]
    if command_rows:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Commands run",
            "columns": ["#", "Command"],
            "rows": command_rows,
            "hold": 3000,
        })
    if limitations:
        scenes.append(objectives_scene("Limitations", [
            {"label": f"Gap {i + 1}", "status": "pending", "detail": str(item)}
            for i, item in enumerate(limitations[:8])
        ]))
    refs = [
        {"label": "Markdown report", "path": data.get("markdown_path", ""), "status": "done"},
        {"label": "Summary JSON", "path": data.get("summary_path", ""), "status": "done"},
        {"label": "Case study", "path": data.get("case_study_path", ""), "status": "done"},
        {"label": "Report artifact", "path": str(data.get("_source", "")), "status": "done"},
    ]
    subtitle = f"Selected {selected.get('profile', '(pending)')} / {selected.get('model', '')}"
    return title_deck("Model Harness Evaluation", subtitle, scenes), refs


def eval_pilot(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    candidates = data.get("candidates") or []
    coverage = data.get("coverage") or []
    intent_suites = data.get("intent_suites") or []
    coverage_jobs = data.get("coverage_jobs") or []
    readiness = data.get("readiness") or {}
    failures = data.get("failures") or []
    sweeps = data.get("confidence_sweeps") or []

    def pct_cell(value: Any) -> str:
        try:
            return f"{float(value) * 100:.1f}%"
        except (TypeError, ValueError):
            return "-"

    candidate_rows = []
    for c in candidates[:12]:
        candidate_rows.append({"cells": [
            c.get("call", ""),
            c.get("profile", ""),
            c.get("model", ""),
            pct_cell(c.get("pass_rate")),
            pct_cell((c.get("comparator_pass_rate") or {}).get("median")),
            num((c.get("p95_latency_ms") or {}).get("median")),
            money((c.get("avg_cost_usd") or {}).get("median")),
            "yes" if c.get("meets_declared_bar") else "no",
        ]})
    coverage_rows = []
    for row in coverage[:12]:
        coverage_rows.append({"cells": [
            row.get("call", ""),
            "yes" if row.get("has_report") else "no",
            ", ".join(row.get("measured_profiles") or []),
            ", ".join(row.get("missing_profiles") or []),
        ]})
    suite_rows = []
    for row in intent_suites[:10]:
        suite_rows.append({"cells": [
            row.get("story", ""),
            num(row.get("fixtures")),
            num(row.get("fixtures_passed")),
            num(row.get("inputs")),
            num(row.get("skipped_inputs")),
        ]})
    job_rows = []
    for row in coverage_jobs[:10]:
        job_rows.append({"cells": [
            row.get("story") or row.get("job", ""),
            num(row.get("instances")),
            num(row.get("corrected")),
            num(row.get("grounding_validated")),
            num(row.get("grounding_cited")),
        ]})
    sweep_rows = []
    for row in sweeps[:8]:
        precision = row.get("precision")
        sweep_rows.append({"cells": [
            row.get("call", ""),
            row.get("profile", ""),
            row.get("model", ""),
            num(row.get("threshold")),
            num(row.get("accepted")),
            num(row.get("false_accepts")),
            "-" if precision is None else pct_cell(precision),
        ]})

    readiness_gaps = []
    for key in ("intent_suites", "mining_profiles"):
        for row in (readiness.get(key) or [])[:8]:
            has_report = row.get("has_report", row.get("has_coverage_job", True))
            if not has_report:
                readiness_gaps.append(row.get("story") or row.get("path") or key)

    scenes = [
        objectives_scene("Pilot status", [
            {"label": "Eval datasets", "status": "done" if data.get("datasets") else "pending", "detail": f"{len(data.get('datasets') or [])} dataset(s) discovered."},
            {"label": "Agent reports", "status": "done" if data.get("reports") else "pending", "detail": f"{len(data.get('reports') or [])} report row(s) loaded."},
            {"label": "Candidates", "status": "done" if candidates else "pending", "detail": f"{len(candidates)} aggregate candidate(s)."},
            {"label": "Readiness gaps", "status": "pending" if readiness_gaps else "done", "detail": f"{len(readiness_gaps)} gap(s)."},
            {"label": "Failures", "status": "failed" if failures else "done", "detail": f"{len(failures)} failure sample(s)."},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Candidate matrix",
            "columns": ["Call", "Profile", "Model", "Pass", "Effectiveness", "p95 latency", "Avg cost", "Bar"],
            "rows": candidate_rows or [{"cells": ["-", "-", "-", "-", "-", "-", "-", "-"]}],
            "hold": 3200,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Coverage by call",
            "columns": ["Call", "Has report", "Measured", "Missing"],
            "rows": coverage_rows or [{"cells": ["-", "no", "-", "-"]}],
            "hold": 2600,
        },
    ]
    if suite_rows:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Intent suites",
            "columns": ["Story", "Fixtures", "Passed", "Inputs", "Skipped"],
            "rows": suite_rows,
            "hold": 2600,
        })
    if job_rows:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Coverage jobs",
            "columns": ["Story", "Instances", "Corrected", "Grounded", "Cited"],
            "rows": job_rows,
            "hold": 2600,
        })
    if sweep_rows:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Confidence sweep",
            "columns": ["Call", "Profile", "Model", "Threshold", "Accepted", "False accepts", "Precision"],
            "rows": sweep_rows,
            "hold": 2800,
        })
    scenes.append(evidence_scene("Review artifacts", [
        {"label": "Summary JSON", "status": "done", "detail": "Machine-readable eval pilot rollup.", "ref": str(data.get("_source", ""))},
    ]))
    refs = [{"label": "Summary JSON", "path": str(data.get("_source", "")), "status": "done"}]
    subtitle = f"{len(candidates)} candidate(s), {len(readiness_gaps)} readiness gap(s)"
    return title_deck("Eval Pilot Report", subtitle, scenes), refs


def cost_report(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    stories = require_list(data, "stories", "cost-report")
    story_rows = []
    intent_rows = []
    total_ops = 0
    measured = 0
    authored = 0
    for row in stories[:18]:
        baseline = row.get("baseline") or {}
        if row.get("measured"):
            measured += 1
        if row.get("measured") and not row.get("recorded", True):
            authored += 1
        total_ops += int(baseline.get("ops_sampled") or 0)
        story_rows.append({"cells": [
            row.get("name", ""),
            money(row.get("story_cost_usd")) if row.get("measured") else "unmeasured",
            money(baseline.get("median_usd")) if baseline.get("ops_sampled") else "-",
            money(baseline.get("p90_usd")) if baseline.get("ops_sampled") else "-",
            money(row.get("savings_median_usd")) if row.get("measured") and baseline.get("ops_sampled") else "-",
            num(baseline.get("ops_sampled")),
            "authored" if row.get("measured") and not row.get("recorded", True) else "recorded" if row.get("measured") else "missing",
        ]})
        for intent in (row.get("intents") or [])[:4]:
            intent_rows.append({"cells": [
                row.get("name", ""),
                intent.get("operation", ""),
                num(intent.get("n")),
                money(intent.get("median_usd")),
                money(intent.get("p90_usd")),
                num(intent.get("sessions")),
            ]})

    reproc = sum(int((row.get("baseline") or {}).get("reprocessing_tokens") or 0) for row in stories)
    scenes = [
        objectives_scene("Cost-report status", [
            {"label": "Story numerators", "status": "done" if measured == len(stories) and stories else "pending", "detail": f"{measured} of {len(stories)} story cost(s) measured from cassettes."},
            {"label": "Raw baseline", "status": "done" if total_ops else "pending", "detail": f"{total_ops} transcript operation(s) sampled."},
            {"label": "Authored cassettes", "status": "pending" if authored else "done", "detail": f"{authored} measured story cost(s) came from record_mode none cassettes."},
            {"label": "Reprocessing tax", "status": "done" if reproc else "pending", "detail": f"{reproc:,} cached input token(s) re-read by raw sessions."},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Per-story savings",
            "columns": ["Story", "Story cost", "Raw median", "Raw p90", "Savings", "Ops", "Cassette"],
            "rows": story_rows or [{"cells": ["-", "-", "-", "-", "-", "0", "-"]}],
            "caption": "Story cost comes from host cassettes; raw cost comes from recorded transcript telemetry.",
            "hold": 3200,
        },
    ]
    if intent_rows:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Intent distributions",
            "columns": ["Story", "Operation", "n", "Median", "p90", "Sessions"],
            "rows": intent_rows[:16],
            "hold": 3000,
        })
    scenes.append(evidence_scene("Review artifacts", [
        {"label": "Markdown report", "status": "done" if data.get("markdown_path") else "pending", "detail": "Human-readable cost report.", "ref": data.get("markdown_path", "")},
        {"label": "Summary JSON", "status": "done", "detail": "Structured input for this deterministic deck.", "ref": str(data.get("_source", ""))},
    ]))
    refs = [
        {"label": "Markdown report", "path": data.get("markdown_path", ""), "status": "done" if data.get("markdown_path") else "pending"},
        {"label": "Summary JSON", "path": str(data.get("_source", "")), "status": "done"},
    ]
    return title_deck("Per-story Cost Report", f"{len(stories)} story(s), {total_ops} sampled raw operation(s)", scenes), refs


def story_qa(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    targets = require_list(data, "targets", "story-qa")
    requested = data.get("project", "all")
    rows = []
    counts = {"validated": 0, "available": 0, "planned": 0, "blocked": 0, "error": 0}
    for target in targets:
        verify = target.get("verify") or {}
        verify_status = str(verify.get("status") or target.get("status") or "planned").lower()
        if verify_status in counts:
            counts[verify_status] += 1
        elif verify_status.startswith("validated"):
            counts["validated"] += 1
        elif verify_status.startswith("blocked"):
            counts["blocked"] += 1
        else:
            counts["planned"] += 1
        rows.append({"cells": [
            target.get("id", ""),
            target.get("stack", ""),
            target.get("run_mode", ""),
            target.get("status", ""),
            verify.get("status", ""),
            verify.get("detail", ""),
        ]})
    evidence_items = [
        {"label": "Markdown report", "status": "done" if data.get("markdown_path") else "pending", "detail": "Human-readable story QA report.", "ref": data.get("markdown_path", "")},
        {"label": "Summary JSON", "status": "done", "detail": "Structured input used to build this deterministic deck.", "ref": str(data.get("_source", ""))},
        {"label": "Product journey catalog", "status": "done", "detail": "Target and perspective registry.", "ref": data.get("catalog", "")},
    ]
    scenes = [
        objectives_scene("QA status", [
            {"label": "Requested scope", "status": "done", "detail": str(requested)},
            {"label": "Validated lanes", "status": "done" if counts["validated"] else "pending", "detail": f"{counts['validated']} target(s)."},
            {"label": "Blocked lanes", "status": "blocked" if counts["blocked"] else "done", "detail": f"{counts['blocked']} target(s)."},
            {"label": "Errors", "status": "failed" if counts["error"] else "done", "detail": f"{counts['error']} target(s)."},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Project lanes",
            "columns": ["Target", "Stack", "Mode", "Catalog", "Verify", "Detail"],
            "rows": rows or [{"cells": ["-", "-", "-", "-", "-", "-"]}],
            "hold": 3000,
        },
        evidence_scene("Review artifacts", evidence_items),
    ]
    refs = [
        {"label": "Markdown report", "path": data.get("markdown_path", ""), "status": "done" if data.get("markdown_path") else "pending"},
        {"label": "Summary JSON", "path": str(data.get("_source", "")), "status": "done"},
        {"label": "Product journey catalog", "path": data.get("catalog", ""), "status": "done"},
    ]
    subtitle = f"{len(targets)} target(s), {counts['validated']} validated, {counts['blocked']} blocked"
    return title_deck("Story QA Report", subtitle, scenes), refs


def session_mining_action(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    patterns = require_list(data, "patterns", "session-mining-action")
    candidates = data.get("candidates") or []
    novel = data.get("novel_promotion_candidates") or []
    watch = data.get("novel_quarantine") or []
    total = data.get("contributors", 1)
    promote_min = data.get("promote_min_contributors", 2)

    verdict_counts: dict[str, int] = {}
    rows = []
    for pattern in patterns[:18]:
        label = pattern.get("verdict", "LATER")
        verdict_counts[label] = verdict_counts.get(label, 0) + 1
        rows.append({"cells": [
            pattern.get("id", ""),
            label,
            num(pattern.get("determinism_priority")),
            f"{pattern.get('contributors', 0)}/{total}",
            num(pattern.get("occurrences")),
            pattern.get("pain", ""),
            num(len(pattern.get("decision_points") or [])),
        ]})

    candidate_rows = []
    for pattern in candidates[:8]:
        gates = pattern.get("decision_points") or []
        signatures = pattern.get("example_signatures") or []
        candidate_rows.append({"cells": [
            pattern.get("id", ""),
            pattern.get("verdict", ""),
            num(pattern.get("determinism_priority")),
            pattern.get("ladder_target", ""),
            "; ".join(gates[:2]),
            "; ".join(signatures[:1]),
        ]})

    scenes = [
        objectives_scene("Mining status", [
            {"label": "Aggregate loaded", "status": "done" if patterns else "pending", "detail": f"{len(patterns)} ranked pattern(s)."},
            {"label": "Build candidates", "status": "next" if candidates else "pending", "detail": f"{len(candidates)} pattern(s) crossed the action threshold."},
            {"label": "Promotion threshold", "status": "done", "detail": f"{promote_min} of {total} contributor(s)."},
            {"label": "Vocabulary updates", "status": "next" if novel else "done", "detail": f"{len(novel)} newly corroborated pattern(s)."},
            {"label": "Watch list", "status": "pending" if watch else "done", "detail": f"{len(watch)} novel pattern(s) awaiting corroboration."},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Build candidates",
            "columns": ["Pattern", "Verdict", "Priority", "Target", "Gates", "Skeleton"],
            "rows": candidate_rows or [{"cells": ["-", "-", "-", "-", "-", "-"]}],
            "hold": 3200,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Full ranking",
            "columns": ["Pattern", "Verdict", "Priority", "Contrib", "Occ", "Pain", "Gates"],
            "rows": rows or [{"cells": ["-", "-", "-", "-", "-", "-", "-"]}],
            "hold": 3200,
        },
        evidence_scene("Review artifacts", [
            {"label": "Aggregate JSON", "status": "done", "detail": "Source ranking and evidence aggregate.", "ref": str(data.get("_source", ""))},
            {"label": "Markdown brief", "status": "done" if data.get("markdown_path") else "pending", "detail": "Prescriptive action brief.", "ref": data.get("markdown_path", "")},
            {"label": "Summary JSON", "status": "done" if data.get("summary_path") else "pending", "detail": "Computed verdicts used by this deck.", "ref": data.get("summary_path", "")},
        ]),
    ]
    refs = [
        {"label": "Aggregate JSON", "path": str(data.get("_source", "")), "status": "done"},
        {"label": "Markdown brief", "path": data.get("markdown_path", ""), "status": "done" if data.get("markdown_path") else "pending"},
        {"label": "Summary JSON", "path": data.get("summary_path", ""), "status": "done" if data.get("summary_path") else "pending"},
    ]
    subtitle = f"{len(candidates)} build candidate(s), {len(patterns)} ranked pattern(s)"
    return title_deck("Session-Mining Action Brief", subtitle, scenes), refs


def session_mining_intent(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    intents = require_list(data, "intents", "session-mining-intent")
    clusters = data.get("clusters") or []
    det = data.get("determinism_counts") or {}
    grounding = data.get("grounding") or {}
    tag_rows = []
    for dim, values in sorted((data.get("tags") or {}).items()):
        if not isinstance(values, dict):
            continue
        top = sorted(values.items(), key=lambda kv: (-kv[1], kv[0]))[:8]
        tag_rows.append({"cells": [dim, ", ".join(f"{k} {v}" for k, v in top)]})
    intent_rows = []
    for row in intents[:16]:
        tags = row.get("tags") or {}
        intent_rows.append({"cells": [
            row.get("instance_id", ""),
            row.get("determinism", ""),
            ", ".join(tags.get("action") or []),
            num((row.get("measured") or {}).get("tool_calls")),
            "; ".join((row.get("agent_gates") or [])[:2]),
            row.get("recipe", ""),
        ]})
    cluster_rows = [{"cells": [num(c.get("count")), c.get("key", "")]} for c in clusters[:10]]
    scenes = [
        objectives_scene("Intent-mining status", [
            {"label": "Intent catalog", "status": "done" if intents else "pending", "detail": f"{len(intents)} intent(s)."},
            {"label": "Deterministic", "status": "done" if det.get("deterministic") else "pending", "detail": f"{det.get('deterministic', 0)} pure tool sequence(s)."},
            {"label": "Agent gated", "status": "next" if det.get("agent-gated") else "done", "detail": f"{det.get('agent-gated', 0)} strict-gate recipe(s)."},
            {"label": "Irreducible LLM", "status": "blocked" if det.get("irreducible-llm") else "done", "detail": f"{det.get('irreducible-llm', 0)} open-ended generation case(s)."},
            {"label": "Grounding", "status": "done" if grounding.get("valid") == grounding.get("cited") else "pending", "detail": f"{grounding.get('valid', 0)}/{grounding.get('cited', 0)} actions validated."},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Intent recipes",
            "columns": ["Instance", "Verdict", "Action tags", "Tools", "Gates", "Recipe"],
            "rows": intent_rows or [{"cells": ["-", "-", "-", "-", "-", "-"]}],
            "hold": 3400,
        },
    ]
    if cluster_rows:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Recurring shapes",
            "columns": ["Count", "Cluster"],
            "rows": cluster_rows,
            "hold": 2600,
        })
    if tag_rows:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Tag distribution",
            "columns": ["Dimension", "Top tags"],
            "rows": tag_rows,
            "hold": 2600,
        })
    scenes.append(evidence_scene("Review artifacts", [
        {"label": "Intents JSON", "status": "done", "detail": "Catalog report.", "ref": data.get("intents_path", "")},
        {"label": "Analysis JSON", "status": "done", "detail": "Per-instance determinism recipes.", "ref": data.get("analysis_path", "")},
        {"label": "Markdown brief", "status": "done" if data.get("markdown_path") else "pending", "detail": "Readable intent brief.", "ref": data.get("markdown_path", "")},
        {"label": "Summary JSON", "status": "done" if data.get("summary_path") else "pending", "detail": "Structured deck input.", "ref": data.get("summary_path", "")},
    ]))
    refs = [
        {"label": "Intents JSON", "path": data.get("intents_path", ""), "status": "done"},
        {"label": "Analysis JSON", "path": data.get("analysis_path", ""), "status": "done"},
        {"label": "Markdown brief", "path": data.get("markdown_path", ""), "status": "done" if data.get("markdown_path") else "pending"},
        {"label": "Summary JSON", "path": data.get("summary_path", ""), "status": "done" if data.get("summary_path") else "pending"},
    ]
    subtitle = f"{len(intents)} intent(s), {det.get('agent-gated', 0)} agent-gated, {det.get('irreducible-llm', 0)} irreducible"
    return title_deck("Session-Mining Intent Brief", subtitle, scenes), refs


def session_idea_mining(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    themes = require_list(data, "themes", "session-idea-mining")
    counts = {"now": 0, "soon": 0, "later": 0}
    total_sessions = 0
    rows = []
    for theme in themes[:16]:
        priority = str(theme.get("priority", "later")).lower()
        counts[priority if priority in counts else "later"] += 1
        sessions = int(theme.get("session_count") or 0)
        total_sessions = max(total_sessions, sessions)
        rows.append({"cells": [
            theme.get("theme", ""),
            priority,
            num(sessions),
            theme.get("target", ""),
            "/".join(theme.get("categories") or []),
            theme.get("summary", ""),
        ]})
    now_rows = []
    for theme in [t for t in themes if str(t.get("priority", "later")).lower() == "now"][:8]:
        now_rows.append({"cells": [
            theme.get("theme", ""),
            theme.get("target", ""),
            theme.get("rationale", ""),
            "; ".join((theme.get("supporting_ideas") or [])[:2]),
        ]})
    scenes = [
        objectives_scene("Idea-mining status", [
            {"label": "Synthesis loaded", "status": "done" if themes else "pending", "detail": f"{len(themes)} theme(s)."},
            {"label": "Now", "status": "next" if counts["now"] else "done", "detail": f"{counts['now']} high-priority theme(s)."},
            {"label": "Soon", "status": "pending" if counts["soon"] else "done", "detail": f"{counts['soon']} next theme(s)."},
            {"label": "Later", "status": "pending" if counts["later"] else "done", "detail": f"{counts['later']} watch-list theme(s)."},
            {"label": "Evidence spread", "status": "done" if total_sessions else "pending", "detail": f"Top theme spans {total_sessions} session(s)."},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Ranked themes",
            "columns": ["Theme", "Priority", "Sessions", "Target", "Categories", "Summary"],
            "rows": rows or [{"cells": ["-", "-", "-", "-", "-", "-"]}],
            "hold": 3400,
        },
    ]
    if now_rows:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Act now",
            "columns": ["Theme", "Target", "Rationale", "Signals"],
            "rows": now_rows,
            "hold": 3000,
        })
    scenes.append(evidence_scene("Review artifacts", [
        {"label": "Synthesis JSON", "status": "done", "detail": "Workflow result used for deterministic rendering.", "ref": str(data.get("_source", ""))},
        {"label": "Markdown brief", "status": "done" if data.get("markdown_path") else "pending", "detail": "Ranked idea brief.", "ref": data.get("markdown_path", "")},
        {"label": "Summary JSON", "status": "done" if data.get("summary_path") else "pending", "detail": "Structured deck input.", "ref": data.get("summary_path", "")},
    ]))
    refs = [
        {"label": "Synthesis JSON", "path": str(data.get("_source", "")), "status": "done"},
        {"label": "Markdown brief", "path": data.get("markdown_path", ""), "status": "done" if data.get("markdown_path") else "pending"},
        {"label": "Summary JSON", "path": data.get("summary_path", ""), "status": "done" if data.get("summary_path") else "pending"},
    ]
    subtitle = f"{len(themes)} theme(s): {counts['now']} now, {counts['soon']} soon, {counts['later']} later"
    return title_deck(data.get("title") or "Session Idea Mining Brief", subtitle, scenes), refs


def workflow(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    title = data.get("title") or data.get("name") or "Workflow Report"
    objectives = data.get("objectives") or []
    artifacts = data.get("artifacts") or data.get("evidence") or []
    next_steps = data.get("next_steps") or []
    rows = []
    for item in data.get("items", [])[:12]:
        rows.append({"cells": [
            item.get("id") or item.get("label") or "",
            item.get("status") or item.get("quality") or "",
            item.get("owner") or item.get("candidate") or "",
            item.get("artifact") or item.get("path") or "",
        ]})
    scenes = [
        objectives_scene("Objective status", objectives or [{"label": "Workflow", "status": "pending", "detail": "No objective list was provided."}]),
        evidence_scene("Review artifacts", artifacts),
    ]
    if rows:
        scenes.append({"type": "table", "variant": "data", "title": "Work items", "columns": ["Item", "Status", "Owner", "Artifact"], "rows": rows, "hold": 2600})
    for media in data.get("media", [])[:6]:
        scenes.append(media_scene(media, "Workflow media"))
    if next_steps:
        scenes.append(objectives_scene("Next steps", [{"label": s.get("label", "next"), "status": "next", "detail": s.get("detail", "")} for s in next_steps]))
    return title_deck(title, data.get("summary", "Deterministic workflow deck"), scenes), [
        {"label": a.get("label", "artifact"), "path": a.get("ref") or a.get("path", ""), "status": a.get("status", "")}
        for a in artifacts
    ]


def feature_demo(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    title = data.get("title") or "Feature Development Demo"
    phases = require_list(data, "phases", "feature-demo")
    media = require_list(data, "media", "feature-demo")
    personas = data.get("personas") or []
    scenes: list[dict[str, Any]] = [
        objectives_scene("Objective status", data.get("objectives") or [
            {"label": "Feature demo", "status": "done" if media else "pending", "detail": f"{len(media)} replay artifact(s) linked."},
            {"label": "Review path", "status": "next", "detail": "Review the embedded replay scenes and linked artifacts."},
        ]),
    ]
    meta_extra: dict[str, Any] = {}
    if personas:
        meta_extra["personas"] = personas
        scenes.append({
            "type": "personas",
            "variant": "cast",
            "title": "Cast",
            "personas": [p.get("id", "") for p in personas if p.get("id")],
            "caption": data.get("cast_caption", ""),
        })
    if phases:
        scenes.append({
            "type": "personas",
            "variant": "use-cases",
            "title": "Feature path",
            "cases": [
                {
                    "who": p.get("who", p.get("persona", "")),
                    "action": p.get("action") or p.get("label", ""),
                    "detail": p.get("detail", p.get("status", "")),
                }
                for p in phases
            ],
        })
    for item in media[:8]:
        scenes.append(media_scene(item, "Feature replay"))
    deck = title_deck(title, data.get("summary", "Feature progress replay deck"), scenes)
    deck["meta"].update(meta_extra)
    refs = [{"label": m.get("title", "media"), "path": m.get("rrweb") or m.get("src") or m.get("path", ""), "status": "done"} for m in media]
    refs.extend({"label": a.get("label", "artifact"), "path": a.get("ref") or a.get("path", ""), "status": a.get("status", "")} for a in data.get("artifacts", []))
    return deck, refs


def bug_report(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    title = data.get("title") or data.get("bug") or "Bug Report"
    evidence = require_list(data, "evidence", "bug-report")
    media = require_list(data, "media", "bug-report")
    if not (evidence or media):
        raise SystemExit("bug-report: evidence or media is required")
    repro = data.get("reproducer", {})
    scenes: list[dict[str, Any]] = [
        objectives_scene("Bug status", [
            {"label": "Triage", "status": status(data.get("triage_status", "done")), "detail": data.get("summary", "")},
            {"label": "Reproducer", "status": "done" if repro else "pending", "detail": repro.get("command", "No reproducer command provided.") if isinstance(repro, dict) else str(repro)},
            {"label": "Next action", "status": "next", "detail": data.get("next_action", "Review linked evidence and assign owner.")},
        ]),
        evidence_scene("Evidence", evidence),
    ]
    if isinstance(repro, dict) and repro:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Reproducer",
            "columns": ["Field", "Value"],
            "rows": [
                {"cells": ["Command", repro.get("command", "-")]},
                {"cells": ["Expected", repro.get("expected", "-")]},
                {"cells": ["Actual", repro.get("actual", "-")]},
            ],
            "hold": 2400,
        })
    for item in media[:4]:
        scenes.append(media_scene(item, "Bug playback"))
    refs = [{"label": e.get("label", "evidence"), "path": e.get("ref") or e.get("path", ""), "status": e.get("status", "")} for e in evidence]
    refs.extend({"label": m.get("title", "playback"), "path": m.get("rrweb") or m.get("src") or m.get("path", ""), "status": "done"} for m in media)
    return title_deck(title, data.get("summary", "Deterministic bug report deck"), scenes), refs


def fix_tests(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    outcome = data.get("outcome", "unknown")
    artifact = data.get("fix_artifact") or {}
    tests_passed = bool(data.get("tests_passed"))
    cycle = data.get("cycle", 0)
    max_cycles = data.get("max_cycles", 0)
    test_log = data.get("test_log", "")
    status_detail = "green" if tests_passed else "red"
    scenes = [
        objectives_scene("Run status", [
            {"label": "Final tests", "status": "done" if tests_passed else "failed", "detail": status_detail},
            {"label": "Outcome", "status": status(outcome), "detail": outcome},
            {"label": "Fix cycles", "status": "done" if tests_passed else "pending", "detail": f"{cycle} / {max_cycles}"},
            {"label": "Human decision", "status": "blocked" if outcome == "blocked" else "done", "detail": "required" if outcome == "blocked" else "not required"},
        ]),
        evidence_scene("Review artifacts", [
            {"label": "Markdown report", "status": "done", "detail": "Human-readable fix-tests report.", "ref": data.get("report_path", "")},
            {"label": "Summary JSON", "status": "done", "detail": "Structured input for this deck.", "ref": str(data.get("_source", ""))},
            {"label": "Test log", "status": "done" if test_log else "pending", "detail": "Newest captured test log.", "ref": test_log},
        ]),
    ]
    if artifact:
        scenes.append({
            "type": "table",
            "variant": "data",
            "title": "Fix artifact",
            "columns": ["Field", "Value"],
            "rows": [
                {"cells": ["Summary", artifact.get("summary_title", "")]},
                {"cells": ["Files changed", ", ".join(artifact.get("files_changed") or []) or "-"]},
                {"cells": ["Fixed tests", ", ".join(artifact.get("fixed_tests") or []) or "-"]},
                {"cells": ["Remaining failures", ", ".join(artifact.get("remaining_failures") or []) or "-"]},
                {"cells": ["Confidence", num(artifact.get("confidence"))]},
            ],
            "hold": 2600,
        })
        if artifact.get("open_questions"):
            scenes.append(objectives_scene("Open questions", [
                {"label": f"Question {idx + 1}", "status": "blocked", "detail": str(q)}
                for idx, q in enumerate(artifact.get("open_questions", [])[:8])
            ]))
    refs = [
        {"label": "Markdown report", "path": data.get("report_path", ""), "status": "done"},
        {"label": "Summary JSON", "path": str(data.get("_source", "")), "status": "done"},
    ]
    if test_log:
        refs.append({"label": "Test log", "path": test_log, "status": "done"})
    return title_deck("fix-tests report", f"{outcome}; tests {status_detail}", scenes), refs


def fanout(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    title = data.get("title") or "Fan-out Job Report"
    items = require_list(data, "items", "fanout")
    if not items:
        raise SystemExit("fanout: items are required")
    counts = {key: 0 for key in FANOUT_STATUSES}
    rows = []
    for item in items:
        item_status = str(item.get("status", "pending")).lower()
        if item_status not in FANOUT_STATUSES:
            raise SystemExit(f"fanout: unsupported status {item_status!r}")
        counts[item_status] += 1
        rows.append({"cells": [
            item.get("id") or item.get("label") or "",
            item_status,
            num(item.get("attempts", "")),
            item.get("owner") or item.get("worker") or "",
            item.get("artifact") or item.get("path") or item.get("trace") or "",
        ]})
    total = len(items)
    scenes = [
        objectives_scene("Job status", [
            {"label": "Succeeded", "status": "done" if counts["succeeded"] else "pending", "detail": f"{counts['succeeded']} of {total} item(s)."},
            {"label": "Failed", "status": "failed" if counts["failed"] else "done", "detail": f"{counts['failed']} item(s)."},
            {"label": "Retried", "status": "pending" if counts["retried"] else "done", "detail": f"{counts['retried']} item(s)."},
            {"label": "Still pending", "status": "pending" if counts["pending"] or counts["running"] else "done", "detail": f"{counts['pending'] + counts['running']} item(s)."},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Fan-out items",
            "columns": ["Item", "Status", "Attempts", "Owner", "Artifact"],
            "rows": rows[:18],
            "caption": "Rows are sourced from the job artifact; the full JSON remains authoritative.",
            "hold": 3200,
        },
    ]
    if data.get("next_steps"):
        scenes.append(objectives_scene("Next steps", [{"label": s.get("label", "next"), "status": "next", "detail": s.get("detail", "")} for s in data["next_steps"]]))
    refs = [{"label": i.get("id") or i.get("label", "item"), "path": i.get("artifact") or i.get("path") or i.get("trace", ""), "status": i.get("status", "")} for i in items]
    return title_deck(title, f"{counts['succeeded']} succeeded, {counts['failed']} failed, {counts['retried']} retried", scenes), refs


def product_journey(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    title = data.get("title") or data.get("program") or "Product Journey Eval"
    targets = require_list(data, "targets", "product-journey")
    perspectives = require_list(data, "perspectives", "product-journey")
    checks = data.get("checks") or {}
    validated = sum(1 for t in targets if status(checks.get(t.get("id", ""), {}).get("status") or t.get("status")) in {"done", "validated"})
    rows = []
    for target in targets:
        target_id = target.get("id", "")
        check = checks.get(target_id, {}) if isinstance(checks, dict) else {}
        rows.append({"cells": [
            target_id,
            target.get("stack", ""),
            check.get("status") or target.get("status", ""),
            target.get("run_mode", ""),
            target.get("manifest") or target.get("validation_command") or target.get("run_command") or "",
        ]})
    perspective_rows = [
        {"cells": [p.get("id", ""), p.get("owner", ""), p.get("status", ""), p.get("description", "")]}
        for p in perspectives
    ]
    scenes = [
        objectives_scene("Objective status", [
            {"label": "Harness", "status": "done", "detail": "tools/product-journey/run.py emits deterministic structured reports."},
            {"label": "Project lanes", "status": "done" if validated == len(targets) else "pending", "detail": f"{validated} of {len(targets)} target(s) validated or cached."},
            {"label": "Hand-refined reference", "status": "done", "detail": data.get("reference_deck", "No reference deck recorded.")},
            {"label": "Product-site journey", "status": "next", "detail": data.get("next_site_journey", "Run the local product site journey when ready.")},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Target lanes",
            "columns": ["Target", "Stack", "Status", "Mode", "Evidence"],
            "rows": rows,
            "hold": 3000,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Perspectives",
            "columns": ["Perspective", "Owner", "Status", "Description"],
            "rows": perspective_rows or [{"cells": ["-", "-", "-", "-"]}],
            "hold": 2600,
        },
        evidence_scene("Review artifacts", [
            {"label": "Reference deck", "status": "done", "detail": "Hand-refined narrative reference; generated reports do not overwrite it.", "ref": data.get("reference_deck", "")},
            {"label": "Catalog", "status": "done", "detail": "Project and perspective registry.", "ref": data.get("catalog", "")},
            {"label": "Run log", "status": "implemented", "detail": "Chronological operator log when status/check modes are run.", "ref": data.get("run_log", "")},
            {"label": "Generated summary", "status": "done", "detail": "Structured input used to build this deck.", "ref": str(data.get("_source", ""))},
        ]),
    ]
    if data.get("next_steps"):
        scenes.append(objectives_scene("Next steps", data["next_steps"]))
    refs = [
        {"label": "Reference deck", "path": data.get("reference_deck", ""), "status": "done"},
        {"label": "Catalog", "path": data.get("catalog", ""), "status": "done"},
        {"label": "Run log", "path": data.get("run_log", ""), "status": "implemented"},
    ]
    return title_deck(title, data.get("summary", "Deterministic product-journey report"), scenes), refs


def dynamic_workflow(data: dict[str, Any]) -> tuple[dict[str, Any], list[dict[str, str]]]:
    workflow_id = data.get("workflow_id", "dynamic-workflow")
    validation = data.get("validation") or {}
    export_status = data.get("status") or ("validated" if validation.get("ok") else "pending")
    artifacts = data.get("artifacts") or []
    lifecycle_rows = [
        {"cells": ["Workflow", workflow_id]},
        {"cells": ["Goal", data.get("goal", "-")]},
        {"cells": ["Slug", data.get("slug", "-")]},
        {"cells": ["Validation", "ok" if validation.get("ok") else "not-ok"]},
        {"cells": ["Export status", export_status]},
        {"cells": ["Launch command", data.get("launch_command", "-")]},
    ]
    artifact_rows = [{"cells": [Path(str(path)).name, str(path)]} for path in artifacts]
    if data.get("app_path"):
        artifact_rows.append({"cells": ["app", data["app_path"]]})
    if data.get("manifest_path"):
        artifact_rows.append({"cells": ["manifest", data["manifest_path"]]})
    if data.get("trace_path"):
        artifact_rows.append({"cells": ["trace", data["trace_path"]]})
    if data.get("events_path"):
        artifact_rows.append({"cells": ["events", data["events_path"]]})
    scenes = [
        objectives_scene("Workflow status", [
            {"label": "Draft generated", "status": "done", "detail": data.get("draft_dir") or data.get("export_path") or workflow_id},
            {"label": "Validation", "status": "done" if validation.get("ok") else "failed", "detail": "; ".join(validation.get("errors", [])) or "Validation passed."},
            {"label": "Launch/export", "status": status(export_status), "detail": data.get("url") or data.get("export_path") or data.get("launch_command", "")},
        ]),
        {
            "type": "table",
            "variant": "data",
            "title": "Lifecycle",
            "columns": ["Field", "Value"],
            "rows": lifecycle_rows,
            "hold": 2800,
        },
        {
            "type": "table",
            "variant": "data",
            "title": "Generated artifacts",
            "columns": ["Artifact", "Path"],
            "rows": artifact_rows or [{"cells": ["receipt", str(data.get("_source", ""))]}],
            "hold": 2800,
        },
    ]
    warnings = data.get("warnings") or validation.get("warnings") or []
    todos = data.get("todos") or []
    if warnings or todos:
        scenes.append(objectives_scene("Follow-ups", [
            *[{"label": "Warning", "status": "pending", "detail": w} for w in warnings],
            *[{"label": "Todo", "status": "next", "detail": t} for t in todos],
        ]))
    refs = [{"label": "Receipt", "path": str(data.get("_source", "")), "status": "done"}]
    refs.extend({"label": Path(str(path)).name, "path": str(path), "status": "done"} for path in artifacts)
    return title_deck(f"Dynamic Workflow: {workflow_id}", f"{export_status}; validation={'ok' if validation.get('ok') else 'not-ok'}", scenes), refs


BUILDERS = {
    "bakeoff-summary": bakeoff_summary,
    "bug-report": bug_report,
    "cost-report": cost_report,
    "dynamic-workflow": dynamic_workflow,
    "eval-pilot": eval_pilot,
    "external-summary": external_summary,
    "fanout": fanout,
    "feature-demo": feature_demo,
    "fix-tests": fix_tests,
    "model-harness": model_harness,
    "onboarding": onboarding,
    "product-journey": product_journey,
    "session-mining-action": session_mining_action,
    "session-mining-intent": session_mining_intent,
    "session-idea-mining": session_idea_mining,
    "story-qa": story_qa,
    "workflow": workflow,
}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--kind", choices=sorted(BUILDERS), required=True)
    ap.add_argument("--input", help="structured JSON input")
    ap.add_argument("--input-json", help="structured JSON input as a string; overrides --input")
    ap.add_argument("--out", help="Slidey JSON spec to write")
    ap.add_argument("--job", help="derive output under .artifacts/<job>/<run-id>/ when --out is omitted")
    ap.add_argument("--run-id", help="run id/suffix for derived artifact paths")
    ap.add_argument("--artifact-root", default=".artifacts", help="artifact root for derived output paths")
    ap.add_argument("--markdown", help="optional Markdown review index; derived with --job when omitted")
    ap.add_argument("--summary-out", help="optional machine-readable build summary")
    args = ap.parse_args(argv)

    if args.input_json:
        data = json.loads(args.input_json)
    elif args.input:
        data = load_json(args.input)
    else:
        raise SystemExit("deterministic_deck.py: --input or --input-json is required")
    if isinstance(data, dict):
        data.setdefault("_source", args.input)
    out_path, markdown_path = artifact_paths(args)
    deck, refs = BUILDERS[args.kind](data)
    write_json(out_path, deck)
    summary = {
        "kind": args.kind,
        "spec_path": out_path,
        "summary": deck["scenes"][0].get("subtitle", ""),
        "title": deck["meta"]["title"],
        "artifacts": refs,
    }
    if markdown_path:
        write_markdown(markdown_path, summary["title"], summary["summary"], refs)
        summary["markdown_path"] = markdown_path
    if args.summary_out:
        write_json(args.summary_out, summary)
    print(json.dumps(summary, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
