#!/usr/bin/env node
// create-mockup: contract §7 item 2 (~/code/POG/.context/mockup-demo-tooling-contract.md).
//
//   node scripts/create-mockup.mjs <scenario.mockup.json> <out.html> [--manifest] [--renderer <renderer.js>]
//
// Deterministic, no-LLM scenario-spec -> self-contained mockup HTML
// generator (kills friction F6: "mockup states are code, not data" --
// ~/code/POG/.context/mockup-rrweb-tooling-brief.md). Also exposed as MCP
// tool `mockup_create` on server.mjs.
//
// With `--manifest`, additionally emits a starter `*.demo.json` (contract
// §4) plus one starter tour JSON per state group (see
// scenario-spec.mjs#groupStates) and a starter slidey deck, all wired to
// pass demo-doctor's states/deck-paths checks immediately and its
// freshness/chapters/estimate checks once `record-tour.mjs` has captured
// clips -- so `create` -> `record-tour` -> `demo-doctor` is a closed loop
// with no hand-editing in between.

import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { spawnSync } from "node:child_process";

import { loadScenario, resolveScenarioSlideyRoot, groupStates, slugify } from "../lib/scenario-spec.mjs";
import { buildMockupHtml, injectGraphProjectionBlocks } from "../lib/mockup-template.mjs";
import { parseObjectLiteralTopKeys } from "../lib/demo-manifest.mjs";

const DEFAULT_DWELL_MS = 2500;
const DEFAULT_VIEWPORT = { width: 1600, height: 900 };
const DEFAULT_TARGET_PORT = 4173;
const DEFAULT_AIR_SEC = 1.5;

function graphProjectionSyncPath(slideyRoot) {
  return path.join(slideyRoot, "tools", "graph-projection-sync.js");
}

/** Wire the graph zone (if the scenario declares zones.graph.projection):
 * prefer an explicit --renderer file (hermetic, no slidey dependency,
 * always wins when given); otherwise shell out to slidey's own
 * tools/graph-projection-sync.js when a slidey checkout is resolvable.
 * Throws a clear error if the scenario wants a projection but neither path
 * is available. No-ops (graph.source: "none") when the scenario has no
 * projection at all. */
function wireGraphProjection(scenario, outAbs, rendererPath) {
  if (!scenario.projectionAbs) return { configured: false, source: "none" };

  if (rendererPath) {
    const rendererAbs = path.resolve(rendererPath);
    const rendererSrc = fs.readFileSync(rendererAbs, "utf8");
    const projectionJson = JSON.parse(fs.readFileSync(scenario.projectionAbs, "utf8"));
    const html = injectGraphProjectionBlocks(fs.readFileSync(outAbs, "utf8"), rendererSrc, projectionJson);
    fs.writeFileSync(outAbs, html);
    return { configured: true, source: "renderer-flag", renderer: rendererAbs, projection: scenario.projectionAbs };
  }

  const slideyRoot = resolveScenarioSlideyRoot(scenario);
  const syncScript = graphProjectionSyncPath(slideyRoot);
  if (!fs.existsSync(syncScript)) {
    throw new Error(
      `scenario declares zones.graph.projection but no slidey checkout is resolvable at "${slideyRoot}" ` +
        `(tried scenario "slidey" field -> SLIDEY_SRC env -> ~/code/slidey) and no --renderer was given`
    );
  }
  const res = spawnSync(process.execPath, [syncScript, outAbs, scenario.projectionAbs], { encoding: "utf8" });
  if (res.error || res.status !== 0) {
    const detail = (res.stderr || res.stdout || "").trim().slice(0, 500);
    throw new Error(
      `slidey graph-projection-sync failed: ${res.error?.message || `exit ${res.status}`}${detail ? `: ${detail}` : ""}`
    );
  }
  return { configured: true, source: "slidey-sync", slideyRoot, projection: scenario.projectionAbs };
}

function buildTourForGroup(scenario, group, stateKeysInGroup, opts) {
  const raw = scenario.raw;
  const steps = stateKeysInGroup.map((key) => {
    const state = raw.states[key];
    return {
      id: key,
      label: state.inspector?.headline || key,
      before: [{ eval: `window.storyboard.setStep('${key}')` }],
      dwellMs: opts.dwellMs,
      kind: "explain"
    };
  });
  return {
    _comment: `generated by create-mockup.mjs for group "${group}"; capture with record-tour.mjs against the co-emitted *.demo.json manifest`,
    target: opts.target,
    startPath: opts.target.readyPath,
    viewport: opts.viewport,
    deviceScaleFactor: 1,
    pace: 1,
    readySelector: "[data-testid=portal]",
    steps
  };
}

function buildDeckScene(scenario, group, stateKeysInGroup, tourOutRel) {
  const raw = scenario.raw;
  return {
    type: "video",
    mode: "fullscreen",
    fit: "contain",
    rrweb: tourOutRel,
    chapters: "auto",
    title: group,
    narration: stateKeysInGroup.map((key) => ({
      chapter: key,
      text: raw.states[key].inspector?.meaning || raw.states[key].inspector?.headline || key
    }))
  };
}

/**
 * Emit a starter *.demo.json manifest, one tour JSON per state group, and a
 * starter slidey deck -- all co-located next to the mockup. Returns
 * { manifest, deck, tours: [{group, tour, out}] } (absolute paths).
 */
function emitManifest(scenario, outAbs, opts) {
  const dir = path.dirname(outAbs);
  const slug = slugify(scenario.raw.title);
  const mockupBase = path.basename(outAbs);
  const port = opts.targetPort ?? DEFAULT_TARGET_PORT;
  const viewport = opts.viewport || DEFAULT_VIEWPORT;
  const target = {
    launch: `python3 -m http.server ${port} --bind 127.0.0.1`,
    addr: `127.0.0.1:${port}`,
    readyPath: `/${mockupBase}`,
    cwd: ".",
    timeoutMs: 30000
  };

  const groups = groupStates(scenario);
  const tourEntries = [];
  const deckScenes = [{ type: "title", title: scenario.raw.title }];

  for (const [group, keys] of groups) {
    const tourFile = `${slug}-${group}.tour.json`;
    const outFile = path.join("clips", `${slug}-${group}.rrweb.json`);
    const tourJson = buildTourForGroup(scenario, group, keys, {
      dwellMs: opts.dwellMs ?? DEFAULT_DWELL_MS,
      target,
      viewport
    });
    fs.writeFileSync(path.join(dir, tourFile), `${JSON.stringify(tourJson, null, 2)}\n`);
    deckScenes.push(buildDeckScene(scenario, group, keys, outFile));
    tourEntries.push({ group, tour: tourFile, out: outFile });
  }

  const deckFile = `${slug}-demo.slidey.json`;
  fs.writeFileSync(path.join(dir, deckFile), `${JSON.stringify({ scenes: deckScenes }, null, 2)}\n`);

  const manifest = {
    version: 1,
    mockup: mockupBase,
    deck: deckFile,
    ...(scenario.raw.slidey ? { slidey: scenario.raw.slidey } : {}),
    airSec: opts.airSec ?? DEFAULT_AIR_SEC,
    target,
    viewport,
    postersDir: path.join("clips", "posters"),
    tours: tourEntries.map((e) => ({ tour: e.tour, out: e.out }))
  };
  const manifestFile = `${slug}.demo.json`;
  fs.writeFileSync(path.join(dir, manifestFile), `${JSON.stringify(manifest, null, 2)}\n`);

  return {
    manifest: path.join(dir, manifestFile),
    deck: path.join(dir, deckFile),
    tours: tourEntries.map((e) => ({ group: e.group, tour: path.join(dir, e.tour), out: path.join(dir, e.out) }))
  };
}

/**
 * Generate a self-contained mockup from a scenario spec. Returns a summary
 * `{ ok, scenario, mockup, states, graph, manifest? }`. Throws on any
 * structural problem (bad scenario, unresolvable graph projection wiring).
 */
export function runCreateMockup(options) {
  const { scenarioPath, outPath, manifest: withManifest, rendererPath, dwellMs, targetPort, viewport, airSec } = options;
  const scenario = loadScenario(scenarioPath);
  const outAbs = path.resolve(outPath);
  fs.mkdirSync(path.dirname(outAbs), { recursive: true });

  const html = buildMockupHtml(scenario);
  fs.writeFileSync(outAbs, html);

  const graph = wireGraphProjection(scenario, outAbs, rendererPath);

  const finalHtml = fs.readFileSync(outAbs, "utf8");
  const stateKeys = parseObjectLiteralTopKeys(finalHtml, "states");
  if (!stateKeys || stateKeys.sort().join(",") !== [...scenario.stateKeys].sort().join(",")) {
    throw new Error(
      `create-mockup: generated states block keys [${(stateKeys || []).join(", ")}] do not match scenario state keys [${scenario.stateKeys.join(", ")}]`
    );
  }

  const summary = {
    ok: true,
    scenario: scenario.path,
    mockup: outAbs,
    states: stateKeys,
    graph
  };

  if (withManifest) {
    const emitted = emitManifest(scenario, outAbs, { dwellMs, targetPort, viewport, airSec });
    summary.manifest = emitted.manifest;
    summary.deck = emitted.deck;
    summary.tours = emitted.tours;
  }

  return summary;
}

function parseArgs(argv) {
  const positional = [];
  const flags = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--manifest") {
      flags.manifest = true;
    } else if (arg === "--renderer") {
      flags.renderer = argv[++i];
    } else if (arg === "--dwell-ms") {
      flags.dwellMs = Number(argv[++i]);
    } else if (arg === "--target-port") {
      flags.targetPort = Number(argv[++i]);
    } else if (arg === "--air-sec") {
      flags.airSec = Number(argv[++i]);
    } else if (arg.startsWith("--")) {
      throw new Error(`unknown flag: ${arg}`);
    } else {
      positional.push(arg);
    }
  }
  return { positional, flags };
}

function main() {
  const { positional, flags } = parseArgs(process.argv.slice(2));
  const [scenarioArg, outArg] = positional;
  if (!scenarioArg || !outArg) {
    console.error("usage: create-mockup.mjs <scenario.mockup.json> <out.html> [--manifest] [--renderer <renderer.js>]");
    process.exit(2);
  }
  try {
    const summary = runCreateMockup({
      scenarioPath: scenarioArg,
      outPath: outArg,
      manifest: Boolean(flags.manifest),
      rendererPath: flags.renderer,
      dwellMs: flags.dwellMs,
      targetPort: flags.targetPort,
      airSec: flags.airSec
    });
    console.log(JSON.stringify(summary, null, 2));
    process.exit(0);
  } catch (err) {
    console.error(`create-mockup: ${err.stack || err.message}`);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) main();
