/**
 * tier2.ts — swarm tier 2: cassette-agent users.
 *
 * Tier 1 (tools/swarm/journey.ts) drives explicit intents only — zero free
 * text, zero routing. Tier 2 adds FREE-TEXT REALISM while staying zero-LLM:
 * the user types a real sentence, and a `--harness replay --recording ...`
 * session (an interpreter harness backed by a hand-authorable recording,
 * NOT the nil-harness `--flow` fixture tier 1 uses) routes it deterministically,
 * with a host cassette answering whatever host.* call the routed path fires.
 *
 * Fixture reuse: rather than hand-authoring a new story/recording/cassette
 * trio, this tier reuses `stories/off-ramp-demo` verbatim — it already
 * exercises exactly the `--harness replay --recording assets/recording.yaml
 * --host-cassette assets/converse-cassette.yaml` posture end-to-end (see
 * off-ramp-video.spec.ts), and its "agent off-ramp" feature is a genuine
 * free-text interaction: an off-menu QUESTION is answered in place (no state
 * change) via host.agent.converse, stubbed by the cassette. The menu itself
 * (browse/status/about) is driven by explicit intents needing no recording
 * entry at all — see `stories/off-ramp-demo/assets/recording.yaml`'s own doc
 * comment — which is exactly the affordance `scriptedMixUser.ts` uses to put
 * a tier-1-STYLE (scripted, zero free text) user on the SAME server.
 *
 * The one wrinkle: `internal/harness/replay.go`'s `ReplayHarness` matches
 * recording entries by EXACT (case-insensitive, trimmed) input text — no
 * fuzzy/embedding match — so tier 1's "prepend a unique isolation marker to
 * the free text" trick (journey.ts / isolation.ts) would silently break the
 * off-ramp's canned recording entry (the marker-bearing string would no
 * longer match ANY entry, falling through to a real, non-deterministic
 * intent-routing attempt). `buildTier2Recording` below derives a SMALL,
 * per-run recording file from the real fixture — one entry per swarm user,
 * each mapping THAT user's own marker-bearing off-menu question to the exact
 * same `clarify: true` / canned-message shape the shipped recording uses —
 * so every user's utterance still resolves deterministically AND still
 * carries a marker the trace-based isolation check (isolation.ts) can look
 * for. The host cassette needs no such per-user variant: it matches
 * `match_on: [handler]` (the call name, not its content — see
 * `stories/off-ramp-demo/assets/converse-cassette.yaml`'s doc comment), so
 * the exact same canned answer already backs every user's question.
 */
import fs from "fs";
import os from "os";
import path from "path";
import type { Page } from "@playwright/test";
import { waitForState } from "../../runstatus/tests/playwright/_helpers/server.js";
import { checkIsolation, type IsolationResult } from "../isolation.js";
import type { TaggedFinding } from "../audit.js";

export const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../../..");
export const OFF_RAMP_STORY_DIR = path.join(repoRoot, "stories", "off-ramp-demo");
export const OFF_RAMP_RECORDING = path.join(OFF_RAMP_STORY_DIR, "assets", "recording.yaml");
export const OFF_RAMP_HOST_CASSETTE = path.join(OFF_RAMP_STORY_DIR, "assets", "converse-cassette.yaml");

/** The real fixture's off-menu question (kept verbatim so the derived
 *  recording's canned `message` stays word-for-word identical to the shipped
 *  demo — only `input` gains a per-user marker prefix). */
export const OFF_MENU_QUESTION = "why should I trust an AI with my project?";
const CANNED_CLARIFY_MESSAGE = "I don't have a menu item for that — let me just answer it.";

export function markerQuestion(marker: string): string {
  return `${marker} :: ${OFF_MENU_QUESTION}`;
}

/**
 * Writes a temp recording YAML (structurally identical to
 * `stories/off-ramp-demo/assets/recording.yaml`, just N entries instead of
 * one) mapping each of `markers`' `markerQuestion` to the same deterministic
 * clarify response the shipped fixture uses. Returns the written path.
 * Deliberately hand-rolled YAML (the shape is four scalar lines per entry)
 * rather than a dependency on a YAML-writing library tools/swarm doesn't
 * have (see tools/swarm/README.md "why no dependencies").
 */
export function buildTier2Recording(markers: string[], outDir: string): string {
  fs.mkdirSync(outDir, { recursive: true });
  const yamlEscape = (s: string): string => JSON.stringify(s); // valid YAML double-quoted scalar
  const entries = markers
    .map(
      (m) =>
        `  - state: desk\n    input: ${yamlEscape(markerQuestion(m))}\n    clarify: true\n    message: ${yamlEscape(CANNED_CLARIFY_MESSAGE)}\n`,
    )
    .join("");
  const doc = [
    "# Generated by tools/swarm/tiers/tier2.ts (buildTier2Recording) — DO NOT EDIT BY HAND.",
    "# One clarify entry per swarm user, derived from stories/off-ramp-demo/assets/recording.yaml",
    "# so each user's marker-bearing off-menu question still resolves deterministically.",
    "kind: recording",
    "app_id: off-ramp-demo",
    "app_version: 0.1.0",
    `generated_at: "${new Date().toISOString()}"`,
    'generator: "tools/swarm/tiers/tier2.ts buildTier2Recording"',
    "min_confidence: 1.00",
    "",
    "entries:",
    entries,
  ].join("\n");
  const outPath = path.join(outDir, "tier2-recording.yaml");
  fs.writeFileSync(outPath, doc);
  return outPath;
}

// ─── Scenario-driven tier-2 compiler (task 3.2, docs/proposals/scenario-foundry.md) ──
//
// buildTier2Recording above always answers the SAME hardcoded off-menu
// question. This section generalizes that to a real "swarm tier-2 compiler":
// given one or more mined `kind: conversation` scenario IR documents (task
// 3.1's tools/session-mining/scenario_compiler.py output — schema/
// scenario_ir.schema.json), it derives one clarify entry per swarm user from
// a scenario's own first-turn text, picked deterministically by
// SWARM_PERSONA_MIX (docs/proposals/scenario-foundry.md's `persona` field).
// This is the wiring the arena swarm plugin's SWARM_PERSONA_MIX/SWARM_FIXTURE
// env vars (tools/arena/arena/plugins/swarm.py, threaded but previously
// unread) were left for — see swarm.py's `_is_tier2`/`_spec_for`.

/** The minimal shape this module reads off a scenario IR document — see
 *  tools/session-mining/schema/scenario_ir.schema.json for the full schema.
 *  Deliberately narrow (no ajv/schema dependency here — see tools/swarm's
 *  README "why no dependencies"); malformed/missing fields are guarded at
 *  load time in loadScenarioFixtures. */
export interface ScenarioFixture {
  id: string;
  persona: string;
  goal: string;
  turns: Array<{ text: string; corrected?: boolean; corrective_ops?: string[] }>;
  expected_effects: string[];
  abandoned: boolean;
}

function isScenarioFixture(v: unknown): v is ScenarioFixture {
  if (typeof v !== "object" || v === null) return false;
  const d = v as Record<string, unknown>;
  return (
    d.kind === "conversation" &&
    typeof d.id === "string" &&
    typeof d.persona === "string" &&
    Array.isArray(d.turns) &&
    d.turns.length > 0 &&
    typeof (d.turns[0] as Record<string, unknown> | undefined)?.text === "string"
  );
}

/** Loads every `scn-*.json` scenario IR document under fixturePath (if it's a
 *  directory) or the single document at fixturePath (if it's a file).
 *  Malformed/non-conversation documents are skipped, not thrown — a
 *  best-effort load mirrors the compiler's own tolerance for a mixed
 *  directory (e.g. MANIFEST.md sitting alongside the scn-*.json files). */
export function loadScenarioFixtures(fixturePath: string): ScenarioFixture[] {
  const stat = fs.statSync(fixturePath);
  const files = stat.isDirectory()
    ? fs
        .readdirSync(fixturePath)
        .filter((f) => f.startsWith("scn-") && f.endsWith(".json"))
        .sort()
        .map((f) => path.join(fixturePath, f))
    : [fixturePath];
  const out: ScenarioFixture[] = [];
  for (const f of files) {
    try {
      const parsed: unknown = JSON.parse(fs.readFileSync(f, "utf8"));
      if (isScenarioFixture(parsed)) {
        out.push({
          id: parsed.id,
          persona: parsed.persona,
          goal: typeof parsed.goal === "string" ? parsed.goal : "",
          turns: parsed.turns,
          expected_effects: Array.isArray(parsed.expected_effects) ? parsed.expected_effects : [],
          abandoned: Boolean(parsed.abandoned),
        });
      }
    } catch {
      // Skip unreadable/malformed files — best-effort load, never fatal.
    }
  }
  return out;
}

/** Splits a comma-separated SWARM_PERSONA_MIX value into trimmed, non-empty
 *  persona ids. `"core-maintainer:heavy"`-style weight suffixes (as arena's
 *  own axis examples use) are accepted but the weight is ignored — this
 *  compiler only uses the mix to SELECT/ORDER scenarios by persona id, not to
 *  weight a distribution. Returns [] for an empty/whitespace-only value. */
export function parsePersonaMix(mix: string): string[] {
  return mix
    .split(",")
    .map((s) => s.split(":")[0].trim())
    .filter((s) => s.length > 0);
}

/** Deterministically picks the scenario backing swarm user `index`. When
 *  `personaMix` is non-empty, prefers scenarios whose persona matches
 *  `personaMix[index % personaMix.length]`; if no scenario matches that
 *  persona, falls back to any scenario matching ANY mix entry; if still none
 *  match, falls back to the full scenario list. Cycles through matches by
 *  `index` so repeated calls are stable and every scenario in a short list
 *  gets used before repeating. Throws if `scenarios` is empty — the caller's
 *  fixture path yielded nothing usable. */
export function selectScenarioForIndex(
  scenarios: ScenarioFixture[],
  personaMix: string[],
  index: number,
): ScenarioFixture {
  if (scenarios.length === 0) {
    throw new Error("tier2: selectScenarioForIndex: no scenario fixtures to select from");
  }
  if (personaMix.length > 0) {
    const wantPersona = personaMix[index % personaMix.length];
    const exact = scenarios.filter((s) => s.persona === wantPersona);
    if (exact.length > 0) return exact[index % exact.length];
    const anyMix = scenarios.filter((s) => personaMix.includes(s.persona));
    if (anyMix.length > 0) return anyMix[index % anyMix.length];
  }
  return scenarios[index % scenarios.length];
}

/** Derives the canned clarify `message` for a scenario's FIRST turn (the one
 *  this compiler always uses as the off-menu question) — mirrors
 *  tools/session-mining/flow_fixture_compiler.py's `canned_answer` so the
 *  same mined signal (corrective_ops / expected_effects / abandonment) reads
 *  the same way whether replayed via `kitsoki test flows` or the swarm. Never
 *  invents content: only reflects fields already on the (redacted) scenario. */
export function scenarioCannedMessage(scenario: ScenarioFixture): string {
  const turn = scenario.turns[0];
  const isOnlyTurn = scenario.turns.length === 1;
  if (turn.corrected && turn.corrective_ops && turn.corrective_ops.length > 0) {
    return `noted — a correction followed (${turn.corrective_ops.join("; ")})`;
  }
  if (isOnlyTurn && scenario.expected_effects.length > 0) {
    return `acknowledged — expected effects: ${scenario.expected_effects.join("; ")}`;
  }
  if (scenario.abandoned && isOnlyTurn) {
    return "acknowledged (scenario ends unresolved in the source session)";
  }
  return CANNED_CLARIFY_MESSAGE;
}

/**
 * The swarm tier-2 compiler proper: given a list of scenario IR documents,
 * a parsed persona mix, and this run's markers, writes a recording YAML with
 * one clarify entry per marker — each mapping that user's own marker-bearing
 * mined utterance to the scenario's own derived canned message. Structurally
 * identical to buildTier2Recording's output (same YAML shape, same `state:
 * desk` target), just sourced from mined scenarios instead of the one
 * hardcoded question.
 */
export function buildTier2RecordingFromScenarios(
  scenarios: ScenarioFixture[],
  personaMix: string[],
  markers: string[],
  outDir: string,
): string {
  fs.mkdirSync(outDir, { recursive: true });
  const yamlEscape = (s: string): string => JSON.stringify(s);
  const entries = markers
    .map((m, i) => {
      const scenario = selectScenarioForIndex(scenarios, personaMix, i);
      const question = `${m} :: ${scenario.turns[0].text}`;
      const message = scenarioCannedMessage(scenario);
      return `  - state: desk\n    input: ${yamlEscape(question)}\n    clarify: true\n    message: ${yamlEscape(message)}\n`;
    })
    .join("");
  const doc = [
    "# Generated by tools/swarm/tiers/tier2.ts (buildTier2RecordingFromScenarios) — DO NOT EDIT BY HAND.",
    "# One clarify entry per swarm user, each sourced from a mined scenario IR",
    "# document (task 3.1) selected by SWARM_PERSONA_MIX, marker-prefixed exactly",
    "# like buildTier2Recording's shipped-question entries.",
    "kind: recording",
    "app_id: off-ramp-demo",
    "app_version: 0.1.0",
    `generated_at: "${new Date().toISOString()}"`,
    'generator: "tools/swarm/tiers/tier2.ts buildTier2RecordingFromScenarios"',
    "min_confidence: 1.00",
    "",
    "entries:",
    entries,
  ].join("\n");
  const outPath = path.join(outDir, "tier2-recording.yaml");
  fs.writeFileSync(outPath, doc);
  return outPath;
}

/**
 * The env-driven entry point swarm-cassette-users.spec.ts calls: when
 * `SWARM_FIXTURE` names a scenario-IR file or directory (see
 * loadScenarioFixtures), builds the recording from those mined scenarios,
 * ordered/selected by `SWARM_PERSONA_MIX` (parsePersonaMix). When
 * `SWARM_FIXTURE` is unset or yields no usable scenarios, falls back to
 * `buildTier2Recording`'s original hardcoded off-menu question — so existing
 * CI runs (which set neither env var) are byte-for-byte unaffected.
 */
export function buildTier2RecordingAuto(
  markers: string[],
  outDir: string,
  env: NodeJS.ProcessEnv = process.env,
): string {
  const fixturePath = env.SWARM_FIXTURE?.trim();
  if (fixturePath) {
    const scenarios = loadScenarioFixtures(fixturePath);
    if (scenarios.length > 0) {
      const personaMix = parsePersonaMix(env.SWARM_PERSONA_MIX ?? "");
      return buildTier2RecordingFromScenarios(scenarios, personaMix, markers, outDir);
    }
  }
  return buildTier2Recording(markers, outDir);
}

/** Makes a fresh scratch dir under the OS tmp root for one run's derived
 *  recording file (kept out of the repo/.artifacts tree — this is a
 *  throwaway input fixture, not a result artifact). */
export function makeTier2ScratchDir(runId: string): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), `kitsoki-swarm-tier2-${runId}-`));
}

export type RpcFn = <T>(method: string, params: Record<string, unknown>) => Promise<T>;
export type AuditFn = (page: Page, state: string) => Promise<TaggedFinding[]>;

const STEP_TIMEOUT_MS = 60000;

async function waitVisible(page: Page, testId: string, timeoutMs = STEP_TIMEOUT_MS) {
  await page.getByTestId(testId).first().waitFor({ state: "visible", timeout: timeoutMs });
}

/** Types `text` into the off-ramp story's free-text floor (NOT
 *  `composer-input` — a MENU room's free-text box is `text-floor-input`, see
 *  off-ramp-video.spec.ts's doc comment) and sends it via the native-setter +
 *  `input` event dispatch pattern every swarm driver uses (Vue v-model
 *  reliability, not a `.fill()` quirk). */
async function sendFreeText(page: Page, text: string): Promise<void> {
  const input = page.getByTestId("text-floor-input").first();
  await input.waitFor({ state: "visible", timeout: STEP_TIMEOUT_MS });
  await input.evaluate((el, value) => {
    const node = el as HTMLInputElement | HTMLTextAreaElement;
    const proto = Object.getPrototypeOf(node);
    const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
    setter?.call(node, value);
    node.dispatchEvent(new Event("input", { bubbles: true }));
  }, text);
  await page.getByTestId("text-floor-send").first().click();
}

export interface CassetteJourneyResult {
  session_id: string;
  states_visited: string[];
  audit_findings: TaggedFinding[];
  duration_ms: number;
}

/** Phase 1 (mirrors journey.ts's openUserSession): mint + open, unthrottled
 *  so every tier-2 user is "concurrently live" alongside tier-1 users on the
 *  same server as soon as it mints. */
export async function openCassetteUserSession(opts: {
  page: Page;
  base: string;
  rpc: RpcFn;
  storyPath: string;
}): Promise<{ session_id: string }> {
  const { page, base, rpc, storyPath } = opts;
  const { session_id } = await rpc<{ session_id: string }>("runstatus.session.new", {
    story_path: storyPath,
  });
  await page.goto(`${base}/#/s/${session_id}/chat`);
  await waitVisible(page, "chat-section");
  await waitForState(page, "desk", STEP_TIMEOUT_MS);
  return { session_id };
}

/**
 * Phase 2: the free-text off-ramp journey. Sends this user's OWN
 * marker-bearing question (matched by `buildTier2Recording`'s derived
 * entry), asserts the off-ramp answered IN PLACE (no state change, menu
 * intact — the off-ramp's whole point), then proves the menu still works
 * with a real explicit-intent transition (browse -> catalogue), auditing
 * each distinct state reached exactly like tier 1.
 */
export async function driveCassetteUserJourney(opts: {
  page: Page;
  session_id: string;
  marker: string;
  audit: AuditFn;
}): Promise<CassetteJourneyResult> {
  const { page, session_id, marker, audit } = opts;
  const t0 = Date.now();
  const states: string[] = [];
  const findings: TaggedFinding[] = [];
  const visited = new Set<string>();

  async function auditOnce(state: string): Promise<void> {
    states.push(state);
    if (visited.has(state)) return;
    visited.add(state);
    findings.push(...(await audit(page, state)));
  }

  await auditOnce("desk");

  await sendFreeText(page, markerQuestion(marker));
  await waitVisible(page, "offramp-bubble");
  const bubble = page.getByTestId("offramp-bubble");
  await bubble.waitFor({ state: "visible", timeout: STEP_TIMEOUT_MS });
  const mode = await bubble.getAttribute("data-mode");
  if (mode !== "offpath") {
    throw new Error(`tier2: expected offramp-bubble data-mode="offpath", got ${JSON.stringify(mode)}`);
  }
  await waitVisible(page, "offramp-chip");
  // THE CONTRAST that proves the off-ramp didn't bounce state: still "desk",
  // menu still present.
  await waitForState(page, "desk", 5000);
  await waitVisible(page, "intent-btn-browse", 5000);
  await auditOnce("desk-offramp-answered");

  // A real explicit-intent transition, needing no recording entry at all —
  // proves this session's menu still works after the free-text detour.
  const browseBtn = page.getByTestId("intent-btn-browse").first();
  await browseBtn.waitFor({ state: "visible", timeout: STEP_TIMEOUT_MS });
  await browseBtn.click();
  await waitForState(page, "catalogue", STEP_TIMEOUT_MS);
  await auditOnce("catalogue");

  return {
    session_id,
    states_visited: states,
    audit_findings: findings,
    duration_ms: Date.now() - t0,
  };
}

/** Same trace-based ground truth as tier 1's `assertIsolated` (isolation.ts)
 *  — re-exported thinly here so tier-2 call sites don't need to reach into
 *  journey.ts (which is tier-1-specific: PRD story states, composer-select
 *  intents). */
export async function assertCassetteIsolated(
  rpc: RpcFn,
  session_id: string,
  otherMarkers: string[],
): Promise<IsolationResult> {
  const trace = await rpc<unknown>("runstatus.session.trace", { session_id });
  return checkIsolation(JSON.stringify(trace), otherMarkers);
}
