package mining

import (
	"context"
	"encoding/json"
)

// DeltaKind is the class of structure a mined recipe proposes. Each kind has a
// lightest rung it lands at (see RungFor); the proposer never picks a heavier
// rung than the kind requires.
type DeltaKind string

const (
	// KindBinding binds an iface.* default to a concrete provider — a rung-1
	// .kitsoki.yaml overrides.bindings delta.
	KindBinding DeltaKind = "binding"
	// KindWorld sets a dev-story knob for this project (judge_mode, doc-profile
	// keys, base_branch) — a rung-1 overrides.world delta.
	KindWorld DeltaKind = "world"
	// KindIntent names a deterministically-routed action (or slot-template
	// synonym) for something done free-form repeatedly. Rung 1 when a synonym;
	// rung 2 when a new intents: entry needs a room (see RungFor).
	KindIntent DeltaKind = "intent"
	// KindStubWire gives a route-back-to-main stub room real content — a rung-2
	// project-tree materialization.
	KindStubWire DeltaKind = "stub-wire"
	// KindGate adds a decider checkpoint at a recurring judgment fork — a rung-2
	// delta (needs a room to host the gate).
	KindGate DeltaKind = "gate"
	// KindDevStoryEnrich lands the delta in the base story — suggestion + opt-in
	// only, never automatic. Shipped as a separate flagged proposal.
	KindDevStoryEnrich DeltaKind = "dev-story-enrich"
)

// Recipe is a scored capture candidate from the ambient session miner
// (docs/proposals/ambient-session-miner.md). This package consumes recipes; it
// does not produce them. The fields here are the subset the propose→apply loop
// needs — the miner owns the full shape.
type Recipe struct {
	// ID is the stable recipe identifier (used for the staging dir + events).
	ID string
	// Priority is the recipe's score; the proposer only acts on recipes at or
	// over the surface threshold.
	Priority float64
	// Kind is the delta class the recipe proposes.
	Kind DeltaKind
	// Target ∈ root-instance|dev-story (store.MiningTarget*).
	Target string
	// Theme is the plain-English decision the recipe captures — fed to the
	// mapper for the dedup classify pass.
	Theme string
	// Summary is a human-readable description carried into the draft prompt.
	Summary string
	// NeedsRoom is true for an intent recipe whose new action needs a room
	// (forces rung 2). Ignored for kinds whose rung is fixed.
	NeedsRoom bool
}

// InventoryRow is one already-modeled structure in the running instance,
// regenerated by grepping the live tree (host.oracle.* call sites + the
// intents: block) — never read from a cached prior pass. The mapper classifies
// a recipe against the inventory; a recipe whose kind+theme collides with a row
// is ALREADY-MODELED and dropped before it surfaces.
type InventoryRow struct {
	// Kind is the structure's class (mirrors DeltaKind values for the kinds the
	// inventory tracks: binding|world|intent|gate).
	Kind DeltaKind
	// Theme is the decision the existing structure covers.
	Theme string
}

// MapStatus is the mapper persona's dedup verdict over a recipe.
type MapStatus string

const (
	// StatusAlreadyModeled means a structure already covers the theme — drop,
	// never surface.
	StatusAlreadyModeled MapStatus = "ALREADY-MODELED"
	// StatusEnrich means a room exists but needs the structure — proceed.
	StatusEnrich MapStatus = "ENRICH"
	// StatusGap means no structure models the theme — proceed.
	StatusGap MapStatus = "GAP"
)

// Mapper is the dedup seam — the dev-story-mining mapper persona in production
// (regenerate the inventory, never from memory), a stub in tests. It classifies
// a recipe against the regenerated inventory.
//
// Implementations MUST return a status; the proposer treats StatusAlreadyModeled
// as a drop and StatusEnrich/StatusGap as proceed.
type Mapper interface {
	Classify(ctx context.Context, recipe Recipe, inventory []InventoryRow) (MapStatus, error)
}

// Drafter is the author seam — the dev-story-mining author persona in
// production (cassette-backed for any real LLM pass), a stub in tests. It drafts
// a concrete delta for a recipe and returns the files to stage (relpath under
// the staging dir → bytes) plus an author_artifact conforming to
// stories/dev-story-mining/schemas/author_artifact.json.
type Drafter interface {
	Draft(ctx context.Context, recipe Recipe, rung int) (DraftResult, error)
}

// DraftResult is what a Drafter returns: the staged files and the
// author_artifact describing them.
type DraftResult struct {
	// Files maps a relpath (relative to the live tree root) → the new/edited
	// bytes the delta writes. These are written into the staging dir first and
	// only copied onto the live tree on accept.
	Files map[string][]byte
	// Artifact is the raw author_artifact JSON (files_changed, flows_green,
	// summary_markdown). Validated against author_artifact.json before surfacing.
	Artifact json.RawMessage
}
