// Package host — journal plumbing for oracle call tracing.
//
// This file provides:
//  1. Context keys and helpers to inject a journal.Writer and an oracle call
//     context (session ID, turn, state path) into the oracle handler context.
//  2. OracleCallBody — the full payload written to KindOracleCall journal
//     entries.
//  3. appendOracleCallJournal — the one-stop write helper called by each
//     oracle verb after it completes.
//  4. truncateField — enforces the 64 KiB per-field cap mandated by the
//     runstatus backend spec.
//
// Design notes:
//   - Journal writes are best-effort: if journalWriter is nil (tests / CLI
//     paths that don't wire a journal) the write is silently skipped.
//   - String fields are capped at 64 KiB. When truncated, the suffix
//     "\n[truncated N bytes]" is appended so consumers know the field is
//     partial.
//   - call_id is a per-call UUID generated by the verb before it starts the
//     oracle subprocess. The lean slog oracle.<verb>.complete record carries
//     the same call_id so export-status can correlate slog ↔ journal.
package host

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"kitsoki/internal/app"
	"kitsoki/internal/journal"
)

// ── String field cap ─────────────────────────────────────────────────────────

const oracleFieldCap = 64 * 1024 // 64 KiB

// truncateField caps s to oracleFieldCap bytes. When truncated the suffix
// "\n[truncated N bytes]" is appended. The result is always valid UTF-8
// because we truncate at byte boundaries, not rune boundaries; callers
// that produce UTF-8 inputs will see at most one mangled multi-byte rune at
// the cut point, which is acceptable for tracing data.
func truncateField(s string) string {
	if len(s) <= oracleFieldCap {
		return s
	}
	n := len(s) - oracleFieldCap
	return s[:oracleFieldCap] + fmt.Sprintf("\n[truncated %d bytes]", n)
}

// ── Context keys ─────────────────────────────────────────────────────────────

// oracleJournalWriterKey is the context key for a journal.Writer injected
// into oracle handler calls.
type oracleJournalWriterKey struct{}

// WithOracleJournalWriter returns a child context carrying w. The oracle
// handlers call JournalWriterFromOracleCtx to retrieve it. Nil is a safe
// no-op.
func WithOracleJournalWriter(ctx context.Context, w journal.Writer) context.Context {
	if w == nil {
		return ctx
	}
	return context.WithValue(ctx, oracleJournalWriterKey{}, w)
}

// JournalWriterFromOracleCtx returns the journal.Writer previously injected
// with WithOracleJournalWriter, or nil if none was injected.
func JournalWriterFromOracleCtx(ctx context.Context) journal.Writer {
	w, _ := ctx.Value(oracleJournalWriterKey{}).(journal.Writer)
	return w
}

// OracleCallCtx carries session-level identifiers needed to populate journal
// entries from within oracle handlers (which don't have direct access to the
// orchestrator's session/turn state).
type OracleCallCtx struct {
	SessionID app.SessionID
	Turn      app.TurnNumber
	StatePath app.StatePath
}

// oracleCallCtxKey is the context key for an OracleCallCtx.
type oracleCallCtxKey struct{}

// WithOracleCallCtx returns a child context carrying oc.
func WithOracleCallCtx(ctx context.Context, oc OracleCallCtx) context.Context {
	return context.WithValue(ctx, oracleCallCtxKey{}, oc)
}

// OracleCallCtxFrom returns the OracleCallCtx previously injected with
// WithOracleCallCtx, or a zero value if none was injected.
func OracleCallCtxFrom(ctx context.Context) OracleCallCtx {
	oc, _ := ctx.Value(oracleCallCtxKey{}).(OracleCallCtx)
	return oc
}

// ── Payload types ─────────────────────────────────────────────────────────────

// OracleCallBody is the journal body for KindOracleCall entries.
// All string fields are capped at 64 KiB before writing.
type OracleCallBody struct {
	// Identity
	CallID string `json:"call_id"` // per-call UUID; correlates with slog oracle.<verb>.complete
	Verb   string `json:"verb"`    // decide|extract|ask|task|converse
	Agent  string `json:"agent,omitempty"`
	Model  string `json:"model,omitempty"`

	// TaskTraceID (task verb only): the UUID that links task.tool / task.end
	// slog events to this oracle.task call. Present only when Verb == "task".
	TaskTraceID string `json:"task_trace_id,omitempty"`

	// Timing and token usage
	DurationMS     int64   `json:"duration_ms"`
	PromptTokens   int     `json:"prompt_tokens,omitempty"`
	ResponseTokens int     `json:"response_tokens,omitempty"`
	CostUSD        float64 `json:"cost_usd,omitempty"`

	// Full prompt content (capped)
	SystemPrompt string `json:"system_prompt,omitempty"`
	Prompt       string `json:"prompt,omitempty"`

	// Verb-specific input descriptor (serialised as JSON object)
	Input json.RawMessage `json:"input,omitempty"`

	// Full response payload (serialised as JSON object)
	Response json.RawMessage `json:"response,omitempty"`

	// Error string when the call failed (may coexist with partial Response)
	Error string `json:"error,omitempty"`
}

// ── Write helper ──────────────────────────────────────────────────────────────

// appendOracleCallJournal writes a KindOracleCall entry to the journal writer
// in ctx (if any). It is safe to call when no journal writer is wired — the
// write is silently skipped. Field caps are applied before writing.
func appendOracleCallJournal(ctx context.Context, ts time.Time, seq int, body OracleCallBody) {
	jw := JournalWriterFromOracleCtx(ctx)
	if jw == nil {
		return
	}
	oc := OracleCallCtxFrom(ctx)

	// Apply field caps.
	body.SystemPrompt = truncateField(body.SystemPrompt)
	body.Prompt = truncateField(body.Prompt)

	raw, err := json.Marshal(body)
	if err != nil {
		return // marshal failure → skip silently
	}

	e := journal.Entry{
		Ts:      ts,
		Session: oc.SessionID,
		Turn:    oc.Turn,
		Seq:     seq,
		Kind:    journal.KindOracleCall,
		Body:    json.RawMessage(raw),
	}
	_ = jw.Append(e)
}

// marshalInput marshals the verb-specific input descriptor to JSON, returning
// nil on error.
func marshalInput(v any) json.RawMessage {
	if v == nil {
		return nil
	}
	b, err := json.Marshal(v)
	if err != nil {
		return nil
	}
	return json.RawMessage(b)
}

// marshalResponse marshals the verb-specific response descriptor to JSON,
// returning nil on error.
func marshalResponse(v any) json.RawMessage {
	return marshalInput(v) // same logic
}
